{-# LANGUAGE OverloadedStrings #-}

module ExplorerPage (
  renderExplorerPageBS,
) where

import Data.ByteString.Lazy (ByteString)
import qualified Data.ByteString.Lazy.Char8 as LBS
import qualified Data.Text as Text
import qualified Data.Text.Encoding as Text.Encoding

-- | Render the deployment explorer HTML page.
-- Loaded via middleware on GET / with Accept: text/html.
-- The page loads /.webmcp/embed.js which fetches all deployments and registers tools.
renderExplorerPageBS :: ByteString
renderExplorerPageBS = LBS.fromStrict $ Text.Encoding.encodeUtf8 $ Text.unlines
  [ "<!DOCTYPE html>"
  , "<html lang=\"en\">"
  , "<head>"
  , "  <meta charset=\"utf-8\">"
  , "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
  , "  <title>L4 Deployments</title>"
  , "  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">"
  , "  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>"
  , "  <link href=\"https://fonts.googleapis.com/css2?family=Merriweather:wght@700&display=swap\" rel=\"stylesheet\">"
  , "  <style>"
  , "    * { box-sizing: border-box; margin: 0; padding: 0; }"
  , "    body { font-family: system-ui, -apple-system, sans-serif; max-width: 960px; margin: 0 auto; padding: 2rem; color: #1a1a1a; }"
  , "    h1, .info h2 { font-family: 'Merriweather', system-ui, -apple-system, sans-serif; }"
  , "    h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }"
  , "    .status { padding: 0.75rem 1rem; border-radius: 0.5rem; margin-bottom: 1.5rem; font-size: 0.875rem; }"
  , "    .status.ok { background: #e8f5e9; color: #2e7d32; }"
  , "    .status.warn { background: #fff3e0; color: #e65100; }"
  , "    .status.loading { background: #e3f2fd; color: #1565c0; }"
  , "    h2 { font-size: 1.125rem; margin: 1.5rem 0 0.75rem; }"
  , "    h3 { font-size: 1rem; cursor: pointer; }"
  , "    h3:hover { color: #1565c0; }"
  , "    input[type=search] { width: 100%; padding: 0.5rem 0.75rem; border: 1px solid #ddd; border-radius: 0.375rem; font-size: 0.875rem; margin-bottom: 1rem; }"
  , "    table { width: 100%; border-collapse: collapse; font-size: 0.875rem; margin-bottom: 1rem; }"
  , "    th { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 2px solid #ddd; font-weight: 600; }"
  , "    td { padding: 0.5rem 0.75rem; border-bottom: 1px solid #eee; }"
  , "    tr:hover td { background: #f5f5f5; }"
  , "    .tag { display: inline-block; padding: 0.125rem 0.5rem; border-radius: 999px; font-size: 0.75rem; font-weight: 500; }"
  , "    .tag-bool { background: #e8f5e9; color: #2e7d32; }"
  , "    .tag-num { background: #e3f2fd; color: #1565c0; }"
  , "    .tag-str { background: #fce4ec; color: #c62828; }"
  , "    .tag-deontic { background: #f3e5f5; color: #6a1b9a; }"
  , "    .tag-other { background: #f5f5f5; color: #616161; }"
  , "    .tag-status { font-size: 0.7rem; }"
  , "    .tag-ready { background: #e8f5e9; color: #2e7d32; }"
  , "    .tag-pending { background: #fff3e0; color: #e65100; }"
  , "    .tag-failed { background: #fce4ec; color: #c62828; }"
  , "    .deploy-section { margin-bottom: 0.5rem; border: 1px solid #eee; border-radius: 0.5rem; padding: 0.75rem 1rem; }"
  , "    .deploy-section.collapsed table { display: none; }"
  , "    .deploy-header { display: flex; justify-content: space-between; align-items: center; }"
  , "    .deploy-meta { font-size: 0.8rem; color: #888; }"
  , "    .info { margin-top: 2rem; padding: 1rem; background: #f8f9fa; border-radius: 0.5rem; }"
  , "    .info h2 { margin-top: 0; }"
  , "    .info pre { background: #1a1a1a; color: #e0e0e0; padding: 0.75rem; border-radius: 0.375rem; overflow-x: auto; font-size: 0.8rem; margin: 0.5rem 0; }"
  , "    .info h2 { cursor: pointer; user-select: none; display: flex; align-items: center; gap: 0.4rem; }"
  , "    .info h2:hover { color: #1565c0; }"
  , "    .info h2::before { content: ''; display: inline-block; width: 0.6em; height: 0.6em; background: currentColor; clip-path: polygon(0 0, 100% 50%, 0 100%); transition: transform 0.15s ease; transform: rotate(90deg); flex-shrink: 0; }"
  , "    .info.collapsed h2::before { transform: rotate(0deg); }"
  , "    .info.collapsed .info-body { display: none; }"
  , "    .info .note { font-size: 0.8rem; color: #666; margin-top: 0.5rem; line-height: 1.6; }"
  , "    .info code { background: #e8e8e8; padding: 0.1rem 0.3rem; border-radius: 0.2rem; font-size: 0.8rem; }"
  , "    .info dt { font-weight: 600; margin-top: 0.5rem; font-size: 0.85rem; }"
  , "    .info dd { margin-left: 1rem; font-size: 0.8rem; color: #555; }"
  , "  </style>"
  , "</head>"
  , "<body>"
  , "  <h1>L4 Deployments</h1>"
  , "  <div id=\"status\" class=\"status loading\">Loading deployments...</div>"
  , ""
  , "  <div id=\"deployments-section\" style=\"display:none\">"
  , "    <input type=\"search\" id=\"fn-search\" placeholder=\"Search across all functions...\" />"
  , "    <div id=\"deploy-list\"></div>"
  , "  </div>"
  , ""
  -- WebMCP embed info box
  , "  <div class=\"info collapsed\">"
  , "    <h2>Embed into your website with WebMCP</h2>"
  , "    <p class=\"note info-desc\">Add a script tag to any web page so browser AI agents can discover and call your L4 rules as structured tools.</p>"
  , "    <div class=\"info-body\">"
  , "    <pre id=\"embed-snippet\"></pre>"
  , "    <div class=\"note\">"
  , "      <dl>"
  , "        <dt><code>data-scope</code></dt>"
  , "        <dd>Filter which deployments and functions to register.<br>"
  , "            <code>deployment-id/*</code> all functions in a deployment<br>"
  , "            <code>deployment-id/function-name</code> one specific function<br>"
  , "            Comma-separated for multiple. Default: everything.</dd>"
  , "        <dt><code>data-tools</code></dt>"
  , "        <dd>Tool registration mode:<br>"
  , "            <code>auto</code> (default) discovery always + direct if &le; 20 functions<br>"
  , "            <code>discovery</code> only search/schema/evaluate meta-tools<br>"
  , "            <code>direct</code> only per-function tools<br>"
  , "            <code>all</code> both, always</dd>"
  , "        <dt><code>data-api-key</code></dt>"
  , "        <dd>Add your API key for <a href=\"https://legalese.cloud\">Legalese Cloud</a> deployments. Needs <strong>l4:read</strong> for discovery, <strong>l4:evaluate</strong> to execute.</dd>"
  , "      </dl>"
  , "    </div>"
  , "    </div>"
  , "  </div>"
  , ""
  -- MCP info box
  , "  <div class=\"info collapsed\">"
  , "    <h2>Connect via MCP (Model Context Protocol)</h2>"
  , "    <p class=\"note info-desc\">Use the MCP server endpoint with any MCP-compatible client (Claude Desktop, Cursor, VS Code, etc.).</p>"
  , "    <div class=\"info-body\">"
  , "    <pre id=\"mcp-url\"></pre>"
  , "    <div class=\"note\">"
  , "      <dl>"
  , "        <dt>Org-wide (all deployments)</dt>"
  , "        <dd><code>POST /.mcp</code> &mdash; registers tools for every deployed function.</dd>"
  , "        <dt>Scoped to one deployment</dt>"
  , "        <dd><code>POST /{deployment-id}/.mcp</code> or <code>POST /deployments/{deployment-id}/.mcp</code></dd>"
  , "        <dt>Authentication</dt>"
  , "        <dd>For <a href=\"https://legalese.cloud\">Legalese Cloud</a> deployments, send your API key as <code>Authorization: Bearer sk_...</code>. Requires <strong>l4:read</strong> + <strong>l4:evaluate</strong> permissions.</dd>"
  , "        <dt>Discovery</dt>"
  , "        <dd><code>GET /.well-known/mcp</code> returns the MCP discovery document.</dd>"
  , "      </dl>"
  , "      <p style=\"margin-top: 0.75rem;\"><strong>Example config</strong> (for <code>.claude.json</code>):</p>"
  , "      <pre id=\"mcp-config\"></pre>"
  , "    </div>"
  , "    </div>"
  , "  </div>"
  , ""
  -- REST API info box
  , "  <div class=\"info collapsed\">"
  , "    <h2>Using the REST API</h2>"
  , "    <p class=\"note info-desc\">Evaluate deployed L4 rules via HTTP. Single and batch evaluation endpoints, OpenAPI metadata with scope filtering.</p>"
  , "    <div class=\"info-body\">"
  , "    <div class=\"note\">"
  , "      <dl>"
  , "        <dt>List functions</dt>"
  , "        <dd><code>GET /{deployment-id}/functions</code><br>"
  , "            <code>GET /deployments/{deployment-id}/functions</code></dd>"
  , "        <dt>Evaluate a function</dt>"
  , "        <dd><code>POST /{deployment-id}/{function-name}/evaluation</code><br>"
  , "            <code>POST /deployments/{deployment-id}/functions/{function-name}/evaluation</code><br>"
  , "            Body: <code>{\"arguments\": {\"field-name\": value, ...}}</code><br>"
  , "            Function names with spaces can use hyphens or URL-encoding (<code>check-person</code>, <code>check%20person</code>).</dd>"
  , "        <dt>Batch evaluation</dt>"
  , "        <dd><code>POST /{deployment-id}/{function-name}/evaluation/batch</code><br>"
  , "            <code>POST /deployments/{deployment-id}/functions/{function-name}/evaluation/batch</code></dd>"
  , "        <dt>OpenAPI metadata (all deployments)</dt>"
  , "        <dd><code>GET /openapi.json</code> &mdash; all functions with parameter schemas.<br>"
  , "            <code>GET /openapi.json?scope={deployment-id}/*</code> &mdash; filter to one deployment.<br>"
  , "            <code>GET /openapi.json?scope={deployment-id}/{function-name}</code> &mdash; filter to one function.<br>"
  , "            Comma-separated for multiple scopes.</dd>"
  , "        <dt>OpenAPI metadata (deployment scoped)</dt>"
  , "        <dd><code>GET /{deployment-id}/openapi.json</code><br>"
  , "            <code>GET /deployments/{deployment-id}/openapi.json</code></dd>"
  , "        <dt>Authentication</dt>"
  , "        <dd>For <a href=\"https://legalese.cloud\">Legalese Cloud</a>, send <code>Authorization: Bearer sk_...</code>. Needs <strong>l4:read</strong> to list, <strong>l4:evaluate</strong> to execute.</dd>"
  , "      </dl>"
  , "    </div>"
  , "    </div>"
  , "  </div>"
  , ""
  -- Deploy info box
  , "  <div class=\"info collapsed\">"
  , "    <h2>Deploying L4 rules</h2>"
  , "    <p class=\"note info-desc\">Upload zip archives (bundles) of <code>.l4</code> files to create or update deployments.</p>"
  , "    <div class=\"info-body\">"
  , "    <div class=\"note\">"
  , "      <dl>"
  , "        <dt>Create or replace a deployment</dt>"
  , "        <dd><code>POST /deployments</code> &mdash; multipart form with <code>id</code> field and <code>sources</code> zip file.<br>"
  , "            <code>PUT /{deployment-id}</code> &mdash; replace an existing deployment.</dd>"
  , "        <dt>Check deployment status</dt>"
  , "        <dd><code>GET /{deployment-id}</code><br>"
  , "            <code>GET /deployments/{deployment-id}</code><br>"
  , "            Returns status (<code>ready</code>, <code>pending</code>, or <code>failed</code>) and function count.</dd>"
  , "        <dt>Delete a deployment</dt>"
  , "        <dd><code>DELETE /{deployment-id}</code><br>"
  , "            <code>DELETE /deployments/{deployment-id}</code></dd>"
  , "        <dt>Authentication</dt>"
  , "        <dd>For <a href=\"https://legalese.cloud\">Legalese Cloud</a>, send <code>Authorization: Bearer sk_...</code>. Requires <strong>l4:deploy</strong> permission.</dd>"
  , "      </dl>"
  , "      <p style=\"margin-top: 0.75rem;\"><strong>Example</strong> (deploy via curl):</p>"
  , "      <pre id=\"deploy-example\"></pre>"
  , "    </div>"
  , "    </div>"
  , "  </div>"
  , ""
  , "  <script>"
  , "    // Collapsible info boxes"
  , "    document.querySelectorAll('.info h2').forEach(function(h2) {"
  , "      h2.addEventListener('click', function() { h2.parentElement.classList.toggle('collapsed'); });"
  , "    });"
  , ""
  , "    var BASE_URL = window.location.origin;"
  , "    document.getElementById('embed-snippet').textContent = '<script src=\"' + BASE_URL + '/.webmcp/embed.js\" data-scope=\"*\" data-tools=\"auto\" data-api-key=\"sk_...\"></' + 'script>';"
  , "    document.getElementById('mcp-url').textContent = BASE_URL + '/.mcp';"
  , "    document.getElementById('mcp-config').textContent = JSON.stringify({ mcpServers: { 'l4-rules': { type: 'http', url: BASE_URL + '/.mcp', headers: { Authorization: 'Bearer sk_...' } } } }, null, 2);"
  , "    document.getElementById('deploy-example').textContent = 'curl -X POST ' + BASE_URL + '/deployments \\\\\\n  -F id=my-rules \\\\\\n  -F sources=@bundle.zip';"
  , ""
  , "    window.addEventListener('webmcp-ready', function(e) {"
  , "      var deployments = e.detail.deployments;"
  , "      var allFns = e.detail.functions;"
  , "      var statusEl = document.getElementById('status');"
  , "      var totalFns = allFns.length;"
  , ""
  , "      function esc(s) { var d = document.createElement('div'); d.textContent = s; return d.innerHTML; }"
  , "      function tagClass(rt) { rt = (rt || '').toUpperCase(); return rt === 'BOOLEAN' ? 'tag-bool' : rt === 'NUMBER' ? 'tag-num' : rt === 'STRING' ? 'tag-str' : rt === 'DEONTIC' ? 'tag-deontic' : 'tag-other'; }"
  , ""
  , "      var container = document.getElementById('deploy-list');"
  , "      container.innerHTML = '';"
  , ""
  , "      if (deployments.length === 0) {"
  , "        container.innerHTML = '<div style=\"padding: 1rem 1rem;\"><p style=\"color: #666; font-size: 0.95rem; margin-bottom: 0.25rem;\">No deployments found.</p><p style=\"color: #999; font-size: 0.8rem;\">Upload an L4 bundle via <code style=\"background:#e8e8e8;padding:0.1rem 0.3rem;border-radius:0.2rem;font-size:0.8rem;\">POST /deployments</code> to get started.</p></div>';"
  , "      }"
  , ""
  , "      deployments.forEach(function(dep) {"
  , "        var section = document.createElement('div');"
  , "        section.className = 'deploy-section collapsed';"
  , "        section.dataset.deploymentId = dep.id;"
  , "        var fns = allFns.filter(function(f) { return f.deployment === dep.id; });"
  , "        var statusTag = dep.status === 'ready' ? 'tag-ready' : dep.status === 'pending' ? 'tag-pending' : 'tag-failed';"
  , "        section.innerHTML = '<div class=\"deploy-header\"><h3>' + esc(dep.id) + ' <span class=\"tag tag-status ' + statusTag + '\">' + esc(dep.status) + '</span> <span class=\"deploy-meta\">' + fns.length + ' functions</span></h3></div>' +"
  , "          '<table><thead><tr><th>Name</th><th>Return</th><th>Description</th></tr></thead><tbody>' +"
  , "          fns.map(function(fn) { var rt = (fn.returnType || '').toUpperCase(); return '<tr><td>' + esc(fn.name) + '</td><td><span class=\"tag ' + tagClass(rt) + '\">' + esc(rt) + '</span></td><td>' + esc(fn.description) + '</td></tr>'; }).join('') +"
  , "          '</tbody></table>';"
  , "        section.querySelector('h3').addEventListener('click', function() { section.classList.toggle('collapsed'); });"
  , "        container.appendChild(section);"
  , "      });"
  , ""
  , "      document.getElementById('deployments-section').style.display = '';"
  , ""
  , "      // Search filter"
  , "      document.getElementById('fn-search').addEventListener('input', function(ev) {"
  , "        var q = (ev.target.value || '').toLowerCase();"
  , "        container.querySelectorAll('.deploy-section').forEach(function(sec) {"
  , "          var rows = sec.querySelectorAll('tbody tr');"
  , "          var anyVisible = false;"
  , "          rows.forEach(function(row) {"
  , "            var text = row.textContent.toLowerCase();"
  , "            var show = !q || text.indexOf(q) >= 0;"
  , "            row.style.display = show ? '' : 'none';"
  , "            if (show) anyVisible = true;"
  , "          });"
  , "          sec.style.display = (!q || anyVisible) ? '' : 'none';"
  , "          if (q && anyVisible) sec.classList.remove('collapsed');"
  , "        });"
  , "      });"
  , ""
  , "      if (e.detail.webmcpRegistered) {"
  , "        statusEl.className = 'status ok';"
  , "        statusEl.textContent = totalFns + ' functions across ' + deployments.length + ' deployments — WebMCP tools are available for you via this browser.';"
  , "      } else {"
  , "        statusEl.className = 'status warn';"
  , "        statusEl.textContent = totalFns + ' functions across ' + deployments.length + ' deployments. WebMCP not supported in this browser.';"
  , "      }"
  , "    });"
  , ""
  , "    window.addEventListener('webmcp-error', function(e) {"
  , "      var statusEl = document.getElementById('status');"
  , "      statusEl.className = 'status warn';"
  , "      statusEl.textContent = 'Failed to load: ' + e.detail.error;"
  , "    });"
  , "  </script>"
  , "  <script src=\"/.webmcp/embed.js\"></script>"
  , "</body>"
  , "</html>"
  ]
