{-# LANGUAGE OverloadedStrings #-}

module WebMCPPage (
  RawHtml (..),
  RawJs (..),
  HTML,
  JavaScript,
  renderAgentPage,
  renderWebMCPScript,
) where

import Data.ByteString.Lazy (ByteString)
import qualified Data.ByteString.Lazy.Char8 as LBS
import Data.Text (Text)
import qualified Data.Text as Text
import qualified Data.Text.Encoding as Text.Encoding
import Network.HTTP.Media ((//), (/:))
import Servant (Accept (..), MimeRender (..))

-- | HTML content type for Servant.
data HTML

instance Accept HTML where
  contentType _ = "text" // "html" /: ("charset", "utf-8")

-- | JavaScript content type for Servant.
data JavaScript

instance Accept JavaScript where
  contentType _ = "application" // "javascript" /: ("charset", "utf-8")

-- | Raw HTML response.
newtype RawHtml = RawHtml { unRawHtml :: ByteString }

instance MimeRender HTML RawHtml where
  mimeRender _ (RawHtml bs) = bs

-- | Raw JavaScript response.
newtype RawJs = RawJs { unRawJs :: ByteString }

instance MimeRender JavaScript RawJs where
  mimeRender _ (RawJs bs) = bs

-- | Render the WebMCP agent HTML page for a deployment.
renderAgentPage :: Text -> RawHtml
renderAgentPage deploymentId = RawHtml $ LBS.fromStrict $ Text.Encoding.encodeUtf8 $ Text.unlines
  [ "<!DOCTYPE html>"
  , "<html lang=\"en\">"
  , "<head>"
  , "  <meta charset=\"utf-8\">"
  , "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
  , "  <title>L4 Rules as WebMCP — " <> escapeHtml deploymentId <> "</title>"
  , "  <style>"
  , "    * { box-sizing: border-box; margin: 0; padding: 0; }"
  , "    body { font-family: system-ui, -apple-system, sans-serif; max-width: 960px; margin: 0 auto; padding: 2rem; color: #1a1a1a; }"
  , "    h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }"
  , "    .meta { color: #666; font-size: 0.875rem; margin-bottom: 1.5rem; }"
  , "    .status { padding: 0.75rem 1rem; border-radius: 0.5rem; margin-bottom: 1.5rem; font-size: 0.875rem; }"
  , "    .status.ok { background: #e8f5e9; color: #2e7d32; }"
  , "    .status.warn { background: #fff3e0; color: #e65100; }"
  , "    .status.loading { background: #e3f2fd; color: #1565c0; }"
  , "    h2 { font-size: 1.125rem; margin: 1.5rem 0 0.75rem; }"
  , "    input[type=search] { width: 100%; padding: 0.5rem 0.75rem; border: 1px solid #ddd; border-radius: 0.375rem; font-size: 0.875rem; margin-bottom: 1rem; }"
  , "    table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }"
  , "    th { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 2px solid #ddd; font-weight: 600; }"
  , "    td { padding: 0.5rem 0.75rem; border-bottom: 1px solid #eee; }"
  , "    tr:hover td { background: #f5f5f5; }"
  , "    .tag { display: inline-block; padding: 0.125rem 0.5rem; border-radius: 999px; font-size: 0.75rem; font-weight: 500; }"
  , "    .tag-bool { background: #e8f5e9; color: #2e7d32; }"
  , "    .tag-num { background: #e3f2fd; color: #1565c0; }"
  , "    .tag-str { background: #fce4ec; color: #c62828; }"
  , "    .tag-deontic { background: #f3e5f5; color: #6a1b9a; }"
  , "    .tag-other { background: #f5f5f5; color: #616161; }"
  , "    .embed { margin-top: 2rem; padding: 1rem; background: #f8f9fa; border-radius: 0.5rem; }"
  , "    .embed h3 { font-size: 0.875rem; margin-bottom: 0.5rem; }"
  , "    .embed pre { background: #1a1a1a; color: #e0e0e0; padding: 0.75rem; border-radius: 0.375rem; overflow-x: auto; font-size: 0.8rem; }"
  , "    .embed .note { font-size: 0.8rem; color: #666; margin-top: 0.5rem; }"
  , "    .footer { padding-top: 1.5rem; font-size: 0.8rem; color: #888; }"
  , "    .footer a { color: #1565c0; text-decoration: none; }"
  , "    .footer a:hover { text-decoration: underline; }"
  , "  </style>"
  , "</head>"
  , "<body>"
  , "  <h1>L4 Rules as WebMCP</h1>"
  , "  <div class=\"meta\">Deployment: <code>" <> escapeHtml deploymentId <> "</code></div>"
  , "  <div id=\"status\" class=\"status loading\">Loading deployment metadata...</div>"
  , ""
  , "  <div id=\"functions-section\" style=\"display:none\">"
  , "    <h2>Functions (<span id=\"fn-count\">0</span>)</h2>"
  , "    <input type=\"search\" id=\"fn-search\" placeholder=\"Search functions...\" />"
  , "    <table>"
  , "      <thead><tr><th>Name</th><th>Return</th><th>Description</th></tr></thead>"
  , "      <tbody id=\"fn-list\"></tbody>"
  , "    </table>"
  , "  </div>"
  , ""
  , "  <div class=\"embed\">"
  , "    <h3>Embed on your website</h3>"
  , "    <pre id=\"embed-snippet\"></pre>"
  , "    <div class=\"note\">"
  , "      For gated deployments on <a href=\"https://legalese.cloud\">Legalese Cloud</a>, add <code>data-api-key=\"sk_...\"</code> to the script tag.<br>"
  , "      The API key needs <strong>l4:read</strong> permission for tool discovery and <strong>l4:evaluate</strong> permission to execute rules."
  , "    </div>"
  , "  </div>"
  , ""
  , "  <script>"
  , "    const DEPLOYMENT_ID = " <> jsString deploymentId <> ";"
  , "    const BASE_URL = window.location.origin;"
  , "    document.getElementById('embed-snippet').textContent = '<script src=\"' + BASE_URL + '/' + DEPLOYMENT_ID + '/webmcp.js\"></' + 'script>';"
  , ""
  , "    (async () => {"
  , "      const statusEl = document.getElementById('status');"
  , ""
  , "      // Fetch deployment metadata"
  , "      let meta;"
  , "      try {"
  , "        const res = await fetch(BASE_URL + '/deployments/' + DEPLOYMENT_ID + '/openapi.json', { credentials: 'include' });"
  , "        if (!res.ok) throw new Error('HTTP ' + res.status);"
  , "        meta = await res.json();"
  , "      } catch (e) {"
  , "        statusEl.className = 'status warn';"
  , "        statusEl.textContent = 'Failed to load deployment: ' + e.message;"
  , "        return;"
  , "      }"
  , ""
  , "      const fns = meta.metaFunctions;"
  , "      document.getElementById('fn-count').textContent = fns.length;"
  , ""
  , "      // Render function table"
  , "      const tbody = document.getElementById('fn-list');"
  , "      function renderTable(filter) {"
  , "        const q = (filter || '').toLowerCase();"
  , "        tbody.innerHTML = '';"
  , "        for (const fn of fns) {"
  , "          if (q && !fn.fsName.toLowerCase().includes(q) && !(fn.fsDescription || '').toLowerCase().includes(q)) continue;"
  , "          const tr = document.createElement('tr');"
  , "          const rt = (fn.fsReturnType || 'unknown').toUpperCase();"
  , "          const tagClass = rt === 'BOOLEAN' ? 'tag-bool' : rt === 'NUMBER' ? 'tag-num' : rt === 'STRING' ? 'tag-str' : rt === 'DEONTIC' ? 'tag-deontic' : 'tag-other';"
  , "          tr.innerHTML = '<td>' + esc(fn.fsName) + '</td><td><span class=\"tag ' + tagClass + '\">' + esc(rt) + '</span></td><td>' + esc(fn.fsDescription || '') + '</td>';"
  , "          tbody.appendChild(tr);"
  , "        }"
  , "      }"
  , "      renderTable();"
  , "      document.getElementById('functions-section').style.display = '';"
  , "      document.getElementById('fn-search').addEventListener('input', e => renderTable(e.target.value));"
  , ""
  , "      function esc(s) { const d = document.createElement('div'); d.textContent = s; return d.innerHTML; }"
  , ""
  , "      // Check WebMCP support"
  , "      if (!('modelContext' in navigator)) {"
  , "        statusEl.className = 'status warn';"
  , "        statusEl.textContent = fns.length + ' functions loaded. WebMCP not supported in this browser — tools not registered.';"
  , "        return;"
  , "      }"
  , ""
  , "      // Register WebMCP tools"
  , "      registerDiscoveryTools(DEPLOYMENT_ID, BASE_URL, fns);"
  , "      registerDirectTools(DEPLOYMENT_ID, BASE_URL, fns);"
  , ""
  , "      statusEl.className = 'status ok';"
  , "      statusEl.textContent = fns.length + ' direct tools + 3 discovery tools registered via WebMCP.';"
  , "    })();"
  , "  </script>"
  , "  <script src=\"" <> escapeHtml (scriptUrl deploymentId) <> "\"></script>"
  , "</body>"
  , "</html>"
  ]

-- | Render the standalone WebMCP JavaScript for a deployment.
renderWebMCPScript :: Text -> RawJs
renderWebMCPScript deploymentId = RawJs $ LBS.fromStrict $ Text.Encoding.encodeUtf8 $ Text.unlines
  [ "(function() {"
  , "  'use strict';"
  , ""
  , "  if (typeof navigator === 'undefined' || !('modelContext' in navigator)) return;"
  , ""
  , "  var scriptTag = document.currentScript || document.querySelector('script[src*=\"webmcp.js\"]');"
  , "  var apiKey = scriptTag && scriptTag.getAttribute('data-api-key');"
  , "  var deploymentId = " <> jsString deploymentId <> ";"
  , "  var baseUrl = scriptTag && scriptTag.src ? new URL(scriptTag.src).origin : window.location.origin;"
  , ""
  , "  var authHeaders = apiKey ? { 'Authorization': 'Bearer ' + apiKey } : {};"
  , "  var fetchOpts = apiKey ? {} : { credentials: 'include' };"
  , ""
  , "  function doFetch(url, opts) {"
  , "    return fetch(url, Object.assign({}, fetchOpts, { headers: Object.assign({}, authHeaders, (opts && opts.headers) || {}) }, opts || {}));"
  , "  }"
  , ""
  , "  doFetch(baseUrl + '/deployments/' + deploymentId + '/openapi.json')"
  , "    .then(function(r) { return r.json(); })"
  , "    .then(function(meta) {"
  , "      var fns = meta.metaFunctions;"
  , "      window.registerDiscoveryTools(deploymentId, baseUrl, fns);"
  , "      window.registerDirectTools(deploymentId, baseUrl, fns);"
  , "    })"
  , "    .catch(function(e) { console.error('WebMCP: failed to load deployment metadata', e); });"
  , "})();"
  , ""
  , "// Sanitize a name for use as a tool identifier."
  , "// Gemini requires: start with [a-zA-Z_], then [a-zA-Z0-9_.:- ], max 128 chars."
  , "function sanitizeName(name) {"
  , "  var s = name.replace(/[^a-zA-Z0-9_.:-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');"
  , "  if (!s || !/^[a-zA-Z_]/.test(s)) s = '_' + s;"
  , "  return s.substring(0, 128);"
  , "}"
  , ""
  , "// Discovery tools — search, inspect, evaluate"
  , "window.registerDiscoveryTools = function(deploymentId, baseUrl, fns) {"
  , "  var scriptTag = document.currentScript || document.querySelector('script[src*=\"webmcp.js\"]');"
  , "  var apiKey = scriptTag && scriptTag.getAttribute('data-api-key');"
  , "  var authHeaders = apiKey ? { 'Authorization': 'Bearer ' + apiKey } : {};"
  , "  var fetchOpts = apiKey ? {} : { credentials: 'include' };"
  , ""
  , "  var index = fns.map(function(fn) {"
  , "    return {"
  , "      name: fn.fsName,"
  , "      description: fn.fsDescription || '',"
  , "      returnType: fn.fsReturnType || 'unknown',"
  , "      section: fn.fsSection || null,"
  , "      isDeontic: fn.fsIsDeontic || false,"
  , "      parameterNames: Object.keys((fn.fsParameters && fn.fsParameters.properties) || {})"
  , "    };"
  , "  });"
  , ""
  , "  navigator.modelContext.registerTool({"
  , "    name: 'search_rules',"
  , "    description: 'Search ' + fns.length + ' available legal rules by keyword. Returns matching names, descriptions, return types, and parameter names.',"
  , "    inputSchema: {"
  , "      type: 'object',"
  , "      properties: {"
  , "        query: { type: 'string', description: 'Search keyword — matches function names, descriptions, and parameters' }"
  , "      },"
  , "      required: ['query']"
  , "    },"
  , "    execute: function(args) {"
  , "      var q = (args.query || '').toLowerCase();"
  , "      var matches = index.filter(function(fn) {"
  , "        return fn.name.toLowerCase().indexOf(q) >= 0"
  , "          || fn.description.toLowerCase().indexOf(q) >= 0"
  , "          || fn.parameterNames.some(function(p) { return p.toLowerCase().indexOf(q) >= 0; });"
  , "      });"
  , "      return { content: [{ type: 'text', text: JSON.stringify(matches, null, 2) }] };"
  , "    }"
  , "  });"
  , ""
  , "  navigator.modelContext.registerTool({"
  , "    name: 'get_rule_schema',"
  , "    description: 'Get the full parameter schema for a specific rule, including all input fields and their types.',"
  , "    inputSchema: {"
  , "      type: 'object',"
  , "      properties: {"
  , "        function_name: { type: 'string', description: 'Exact function name from search_rules' }"
  , "      },"
  , "      required: ['function_name']"
  , "    },"
  , "    execute: function(args) {"
  , "      return fetch(baseUrl + '/deployments/' + deploymentId + '/functions/' + encodeURIComponent(args.function_name),"
  , "        Object.assign({}, fetchOpts, { headers: authHeaders }))"
  , "        .then(function(r) { return r.json(); })"
  , "        .then(function(data) { return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] }; });"
  , "    }"
  , "  });"
  , ""
  , "  navigator.modelContext.registerTool({"
  , "    name: 'evaluate_rule',"
  , "    description: 'Evaluate a legal rule with arguments. Use get_rule_schema first to understand required inputs.',"
  , "    inputSchema: {"
  , "      type: 'object',"
  , "      properties: {"
  , "        function_name: { type: 'string', description: 'Exact function name to evaluate' },"
  , "        arguments: { type: 'object', description: 'Key-value pairs matching the function parameters' }"
  , "      },"
  , "      required: ['function_name', 'arguments']"
  , "    },"
  , "    execute: function(args) {"
  , "      return fetch(baseUrl + '/deployments/' + deploymentId + '/functions/' + encodeURIComponent(args.function_name) + '/evaluation',"
  , "        Object.assign({}, fetchOpts, {"
  , "          method: 'POST',"
  , "          headers: Object.assign({}, authHeaders, { 'Content-Type': 'application/json' }),"
  , "          body: JSON.stringify({ fnArguments: args.arguments })"
  , "        }))"
  , "        .then(function(r) { return r.json(); })"
  , "        .then(function(data) { return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] }; });"
  , "    }"
  , "  });"
  , "};"
  , ""
  , "// Direct tools — one per function"
  , "window.registerDirectTools = function(deploymentId, baseUrl, fns) {"
  , "  var scriptTag = document.currentScript || document.querySelector('script[src*=\"webmcp.js\"]');"
  , "  var apiKey = scriptTag && scriptTag.getAttribute('data-api-key');"
  , "  var authHeaders = apiKey ? { 'Authorization': 'Bearer ' + apiKey } : {};"
  , "  var fetchOpts = apiKey ? {} : { credentials: 'include' };"
  , ""
  , "  fns.forEach(function(fn) {"
  , "    var safeName = sanitizeName(fn.fsName);"
  , "    navigator.modelContext.registerTool({"
  , "      name: safeName,"
  , "      description: (fn.fsDescription || 'Evaluate ' + fn.fsName) + ' [' + fn.fsName + ']',"
  , "      inputSchema: fn.fsParameters || { type: 'object', properties: {}, required: [] },"
  , "      execute: function(args) {"
  , "        return fetch(baseUrl + '/deployments/' + deploymentId + '/functions/' + encodeURIComponent(fn.fsName) + '/evaluation',"
  , "          Object.assign({}, fetchOpts, {"
  , "            method: 'POST',"
  , "            headers: Object.assign({}, authHeaders, { 'Content-Type': 'application/json' }),"
  , "            body: JSON.stringify({ fnArguments: args })"
  , "          }))"
  , "          .then(function(r) { return r.json(); })"
  , "          .then(function(data) { return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] }; });"
  , "      }"
  , "    });"
  , "  });"
  , "};"
  ]

-- | Build the relative script URL for a deployment.
scriptUrl :: Text -> Text
scriptUrl deploymentId = "/deployments/" <> deploymentId <> "/webmcp.js"

-- | Escape text for safe HTML embedding.
escapeHtml :: Text -> Text
escapeHtml = Text.replace "&" "&amp;"
  . Text.replace "<" "&lt;"
  . Text.replace ">" "&gt;"
  . Text.replace "\"" "&quot;"

-- | Encode text as a JavaScript string literal.
jsString :: Text -> Text
jsString t = "\"" <> Text.replace "\\" "\\\\" (Text.replace "\"" "\\\"" (Text.replace "\n" "\\n" t)) <> "\""
