{-# LANGUAGE OverloadedStrings #-}

module WebMCPPage (
  RawHtml (..),
  RawJs (..),
  HTML,
  JavaScript,
  renderExplorerPage,
  renderExplorerPageBS,
  renderOrgWebMCPScript,
) where

import Data.ByteString.Lazy (ByteString)
import qualified Data.ByteString.Lazy.Char8 as LBS
import qualified Data.Text as Text
import qualified Data.Text.Encoding as Text.Encoding
import Network.HTTP.Media ((//), (/:))
import Servant (Accept (..), MimeRender (..))

-- | HTML content type for Servant.
data HTML

instance Accept HTML where
  contentType _ = "text" // "html" /: ("charset", "utf-8")

-- | JavaScript content type for Servant.
data JavaScript

instance Accept JavaScript where
  contentType _ = "application" // "javascript" /: ("charset", "utf-8")

-- | Raw HTML response.
newtype RawHtml = RawHtml { unRawHtml :: ByteString }

instance MimeRender HTML RawHtml where
  mimeRender _ (RawHtml bs) = bs

-- | Raw JavaScript response.
newtype RawJs = RawJs { unRawJs :: ByteString }

instance MimeRender JavaScript RawJs where
  mimeRender _ (RawJs bs) = bs

-- | Render the org-level deployment explorer HTML page.
-- The page loads /.webmcp/embed.js which fetches all deployments and registers tools.
-- The HTML just listens for events and renders the UI.
renderExplorerPage :: RawHtml
renderExplorerPage = RawHtml renderExplorerPageBS

renderExplorerPageBS :: ByteString
renderExplorerPageBS = LBS.fromStrict $ Text.Encoding.encodeUtf8 $ Text.unlines
  [ "<!DOCTYPE html>"
  , "<html lang=\"en\">"
  , "<head>"
  , "  <meta charset=\"utf-8\">"
  , "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
  , "  <title>L4 Deployments</title>"
  , "  <style>"
  , "    * { box-sizing: border-box; margin: 0; padding: 0; }"
  , "    body { font-family: system-ui, -apple-system, sans-serif; max-width: 960px; margin: 0 auto; padding: 2rem; color: #1a1a1a; }"
  , "    h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }"
  , "    .status { padding: 0.75rem 1rem; border-radius: 0.5rem; margin-bottom: 1.5rem; font-size: 0.875rem; }"
  , "    .status.ok { background: #e8f5e9; color: #2e7d32; }"
  , "    .status.warn { background: #fff3e0; color: #e65100; }"
  , "    .status.loading { background: #e3f2fd; color: #1565c0; }"
  , "    h2 { font-size: 1.125rem; margin: 1.5rem 0 0.75rem; }"
  , "    h3 { font-size: 1rem; cursor: pointer; }"
  , "    h3:hover { color: #1565c0; }"
  , "    input[type=search] { width: 100%; padding: 0.5rem 0.75rem; border: 1px solid #ddd; border-radius: 0.375rem; font-size: 0.875rem; margin-bottom: 1rem; }"
  , "    table { width: 100%; border-collapse: collapse; font-size: 0.875rem; margin-bottom: 1rem; }"
  , "    th { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 2px solid #ddd; font-weight: 600; }"
  , "    td { padding: 0.5rem 0.75rem; border-bottom: 1px solid #eee; }"
  , "    tr:hover td { background: #f5f5f5; }"
  , "    .tag { display: inline-block; padding: 0.125rem 0.5rem; border-radius: 999px; font-size: 0.75rem; font-weight: 500; }"
  , "    .tag-bool { background: #e8f5e9; color: #2e7d32; }"
  , "    .tag-num { background: #e3f2fd; color: #1565c0; }"
  , "    .tag-str { background: #fce4ec; color: #c62828; }"
  , "    .tag-deontic { background: #f3e5f5; color: #6a1b9a; }"
  , "    .tag-other { background: #f5f5f5; color: #616161; }"
  , "    .tag-status { font-size: 0.7rem; }"
  , "    .tag-ready { background: #e8f5e9; color: #2e7d32; }"
  , "    .tag-pending { background: #fff3e0; color: #e65100; }"
  , "    .tag-failed { background: #fce4ec; color: #c62828; }"
  , "    .deploy-section { margin-bottom: 0.5rem; border: 1px solid #eee; border-radius: 0.5rem; padding: 0.75rem 1rem; }"
  , "    .deploy-section.collapsed table { display: none; }"
  , "    .deploy-header { display: flex; justify-content: space-between; align-items: center; }"
  , "    .deploy-meta { font-size: 0.8rem; color: #888; }"
  , "    .embed { margin-top: 2rem; padding: 1rem; background: #f8f9fa; border-radius: 0.5rem; }"
  , "    .embed h2 { margin-top: 0; }"
  , "    .embed pre { background: #1a1a1a; color: #e0e0e0; padding: 0.75rem; border-radius: 0.375rem; overflow-x: auto; font-size: 0.8rem; margin: 0.5rem 0; }"
  , "    .embed .note { font-size: 0.8rem; color: #666; margin-top: 0.5rem; line-height: 1.6; }"
  , "    .embed code { background: #e8e8e8; padding: 0.1rem 0.3rem; border-radius: 0.2rem; font-size: 0.8rem; }"
  , "    .embed dt { font-weight: 600; margin-top: 0.5rem; font-size: 0.85rem; }"
  , "    .embed dd { margin-left: 1rem; font-size: 0.8rem; color: #555; }"
  , "  </style>"
  , "</head>"
  , "<body>"
  , "  <h1>L4 Deployments</h1>"
  , "  <div id=\"status\" class=\"status loading\">Loading deployments...</div>"
  , ""
  , "  <div id=\"deployments-section\" style=\"display:none\">"
  , "    <input type=\"search\" id=\"fn-search\" placeholder=\"Search across all functions...\" />"
  , "    <div id=\"deploy-list\"></div>"
  , "  </div>"
  , ""
  , "  <div class=\"embed\">"
  , "    <h2>Embed into your website as WebMCP</h2>"
  , "    <pre id=\"embed-snippet\"></pre>"
  , "    <div class=\"note\">"
  , "      <dl>"
  , "        <dt><code>data-scope</code></dt>"
  , "        <dd>Filter which deployments and functions to register.<br>"
  , "            <code>deploy-id/*</code> all functions in a deployment<br>"
  , "            <code>deploy-id/function-name</code> one specific function<br>"
  , "            Comma-separated for multiple. Default: everything.</dd>"
  , "        <dt><code>data-tools</code></dt>"
  , "        <dd>Tool registration mode:<br>"
  , "            <code>auto</code> (default) discovery always + direct if &le; 20 functions<br>"
  , "            <code>discovery</code> only search/schema/evaluate meta-tools<br>"
  , "            <code>direct</code> only per-function tools<br>"
  , "            <code>all</code> both, always</dd>"
  , "        <dt><code>data-api-key</code></dt>"
  , "        <dd>Add your API key for <a href=\"https://legalese.cloud\">Legalese Cloud</a> deployments. Needs <strong>l4:read</strong> for discovery, <strong>l4:evaluate</strong> to execute.</dd>"
  , "      </dl>"
  , "    </div>"
  , "  </div>"
  , ""
  , "  <div class=\"embed\">"
  , "    <h2>Connect via MCP (Model Context Protocol)</h2>"
  , "    <p class=\"note\">Use the MCP server endpoint with any MCP-compatible client (Claude Desktop, Cursor, VS Code, etc.).</p>"
  , "    <pre id=\"mcp-url\"></pre>"
  , "    <div class=\"note\">"
  , "      <dl>"
  , "        <dt>Org-wide (all deployments)</dt>"
  , "        <dd><code>POST /.mcp</code> &mdash; registers tools for every deployed function.</dd>"
  , "        <dt>Scoped to one deployment</dt>"
  , "        <dd><code>POST /{deployment-id}/.mcp</code> or <code>POST /deployments/{deployment-id}/.mcp</code></dd>"
  , "        <dt>Authentication</dt>"
  , "        <dd>Send your API key as <code>Authorization: Bearer sk_...</code>. Requires <strong>l4:read</strong> + <strong>l4:evaluate</strong> permissions.</dd>"
  , "        <dt>Discovery</dt>"
  , "        <dd><code>GET /.well-known/mcp/manifest</code> returns the MCP manifest. <code>GET /.well-known/oauth-protected-resource</code> for OAuth discovery.</dd>"
  , "      </dl>"
  , "      <p style=\"margin-top: 0.75rem;\"><strong>Example config</strong> (Claude Desktop / claude_desktop_config.json):</p>"
  , "      <pre id=\"mcp-config\"></pre>"
  , "    </div>"
  , "  </div>"
  , ""
  , "  <script>"
  , "    var BASE_URL = window.location.origin;"
  , "    document.getElementById('embed-snippet').textContent = '<script src=\"' + BASE_URL + '/.webmcp/embed.js\" data-scope=\"*\" data-tools=\"auto\" data-api-key=\"sk_...\"></' + 'script>';"
  , "    document.getElementById('mcp-url').textContent = BASE_URL + '/.mcp';"
  , "    document.getElementById('mcp-config').textContent = JSON.stringify({ mcpServers: { 'l4-rules': { url: BASE_URL + '/.mcp', headers: { Authorization: 'Bearer sk_...' } } } }, null, 2);"
  , ""
  , "    window.addEventListener('webmcp-ready', function(e) {"
  , "      var deployments = e.detail.deployments;"
  , "      var allFns = e.detail.functions;"
  , "      var statusEl = document.getElementById('status');"
  , "      var totalFns = allFns.length;"
  , ""
  , "      function esc(s) { var d = document.createElement('div'); d.textContent = s; return d.innerHTML; }"
  , "      function tagClass(rt) { rt = (rt || '').toUpperCase(); return rt === 'BOOLEAN' ? 'tag-bool' : rt === 'NUMBER' ? 'tag-num' : rt === 'STRING' ? 'tag-str' : rt === 'DEONTIC' ? 'tag-deontic' : 'tag-other'; }"
  , ""
  , "      var container = document.getElementById('deploy-list');"
  , "      container.innerHTML = '';"
  , ""
  , "      deployments.forEach(function(dep) {"
  , "        var section = document.createElement('div');"
  , "        section.className = 'deploy-section collapsed';"
  , "        section.dataset.deploymentId = dep.id;"
  , "        var fns = allFns.filter(function(f) { return f.deployment === dep.id; });"
  , "        var statusTag = dep.status === 'ready' ? 'tag-ready' : dep.status === 'pending' ? 'tag-pending' : 'tag-failed';"
  , "        section.innerHTML = '<div class=\"deploy-header\"><h3>' + esc(dep.id) + ' <span class=\"tag tag-status ' + statusTag + '\">' + esc(dep.status) + '</span> <span class=\"deploy-meta\">' + fns.length + ' functions</span></h3></div>' +"
  , "          '<table><thead><tr><th>Name</th><th>Return</th><th>Description</th></tr></thead><tbody>' +"
  , "          fns.map(function(fn) { var rt = (fn.returnType || '').toUpperCase(); return '<tr><td>' + esc(fn.name) + '</td><td><span class=\"tag ' + tagClass(rt) + '\">' + esc(rt) + '</span></td><td>' + esc(fn.description) + '</td></tr>'; }).join('') +"
  , "          '</tbody></table>';"
  , "        section.querySelector('h3').addEventListener('click', function() { section.classList.toggle('collapsed'); });"
  , "        container.appendChild(section);"
  , "      });"
  , ""
  , "      document.getElementById('deployments-section').style.display = '';"
  , ""
  , "      // Search filter"
  , "      document.getElementById('fn-search').addEventListener('input', function(ev) {"
  , "        var q = (ev.target.value || '').toLowerCase();"
  , "        container.querySelectorAll('.deploy-section').forEach(function(sec) {"
  , "          var rows = sec.querySelectorAll('tbody tr');"
  , "          var anyVisible = false;"
  , "          rows.forEach(function(row) {"
  , "            var text = row.textContent.toLowerCase();"
  , "            var show = !q || text.indexOf(q) >= 0;"
  , "            row.style.display = show ? '' : 'none';"
  , "            if (show) anyVisible = true;"
  , "          });"
  , "          sec.style.display = (!q || anyVisible) ? '' : 'none';"
  , "          if (q && anyVisible) sec.classList.remove('collapsed');"
  , "        });"
  , "      });"
  , ""
  , "      if (e.detail.webmcpRegistered) {"
  , "        statusEl.className = 'status ok';"
  , "        statusEl.textContent = totalFns + ' functions across ' + deployments.length + ' deployments — WebMCP tools registered.';"
  , "      } else {"
  , "        statusEl.className = 'status warn';"
  , "        statusEl.textContent = totalFns + ' functions across ' + deployments.length + ' deployments. WebMCP not supported in this browser.';"
  , "      }"
  , "    });"
  , ""
  , "    window.addEventListener('webmcp-error', function(e) {"
  , "      var statusEl = document.getElementById('status');"
  , "      statusEl.className = 'status warn';"
  , "      statusEl.textContent = 'Failed to load: ' + e.detail.error;"
  , "    });"
  , "  </script>"
  , "  <script src=\"/.webmcp/embed.js\"></script>"
  , "</body>"
  , "</html>"
  ]

-- | Render the org-wide WebMCP JavaScript.
-- Fetches all deployments, applies scope filtering, registers tools.
renderOrgWebMCPScript :: RawJs
renderOrgWebMCPScript = RawJs $ LBS.fromStrict $ Text.Encoding.encodeUtf8 $ Text.unlines
  [ "(function() {"
  , "  'use strict';"
  , ""
  , "  var scriptTag = document.currentScript || document.querySelector('script[src*=\"embed.js\"]');"
  , "  var apiKey = scriptTag && scriptTag.getAttribute('data-api-key');"
  , "  var scope = scriptTag && scriptTag.getAttribute('data-scope');"
  , "  var toolsMode = (scriptTag && scriptTag.getAttribute('data-tools')) || 'auto';"
  , "  var baseUrl = scriptTag && scriptTag.src ? new URL(scriptTag.src).origin : window.location.origin;"
  , ""
  , "  var authHeaders = apiKey ? { 'Authorization': 'Bearer ' + apiKey } : {};"
  , "  var fetchOpts = apiKey ? {} : { credentials: 'include' };"
  , ""
  , "  function doFetch(url, opts) {"
  , "    return fetch(url, Object.assign({}, fetchOpts, { headers: Object.assign({}, authHeaders, (opts && opts.headers) || {}) }, opts || {}));"
  , "  }"
  , ""
  , ""
  , "  function sanitizeName(name, maxLen) {"
  , "    var s = name.replace(/[^a-zA-Z0-9_.-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');"
  , "    if (!s || !/^[a-zA-Z_]/.test(s)) s = '_' + s;"
  , "    return s.substring(0, maxLen || 64);"
  , "  }"
  , ""
  , "  // Sanitize a property name: same replacement char (-) as sanitizeName"
  , "  function sanitizePropName(name) {"
  , "    var s = name.replace(/[^a-zA-Z0-9_.-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');"
  , "    return s || '_unnamed';"
  , "  }"
  , ""
  , "  // Sanitize all property names in a parameters schema and return"
  , "  // { schema, reverseMap } where reverseMap maps sanitized -> original"
  , "  function sanitizeParamsSchema(params) {"
  , "    if (!params || !params.properties) return { schema: params || { type: 'object', properties: {}, required: [] }, reverseMap: {} };"
  , "    var newProps = {}, reverseMap = {};"
  , "    Object.keys(params.properties).forEach(function(origKey) {"
  , "      var safKey = sanitizePropName(origKey);"
  , "      newProps[safKey] = sanitizeParamValue(params.properties[origKey]);"
  , "      if (safKey !== origKey) reverseMap[safKey] = origKey;"
  , "    });"
  , "    var newRequired = (params.required || []).map(sanitizePropName);"
  , "    return {"
  , "      schema: { type: 'object', properties: newProps, required: newRequired },"
  , "      reverseMap: reverseMap"
  , "    };"
  , "  }"
  , ""
  , "  // Recursively sanitize nested property names inside a parameter value"
  , "  function sanitizeParamValue(p) {"
  , "    if (!p) return p;"
  , "    var out = { type: p.type, alias: p.alias, description: p.description };"
  , "    if (p['enum'] && p['enum'].length) out['enum'] = p['enum'];"
  , "    if (p.format) out.format = p.format;"
  , "    if (p.properties) {"
  , "      var nested = {};"
  , "      Object.keys(p.properties).forEach(function(k) {"
  , "        nested[sanitizePropName(k)] = sanitizeParamValue(p.properties[k]);"
  , "      });"
  , "      out.properties = nested;"
  , "    }"
  , "    if (p.propertyOrder) out.propertyOrder = p.propertyOrder.map(sanitizePropName);"
  , "    if (p.items) out.items = sanitizeParamValue(p.items);"
  , "    return out;"
  , "  }"
  , ""
  , "  // Remap sanitized argument keys back to original L4 names"
  , "  function remapArgs(args, reverseMap) {"
  , "    var out = {};"
  , "    Object.keys(args).forEach(function(k) {"
  , "      out[reverseMap[k] || k] = args[k];"
  , "    });"
  , "    return out;"
  , "  }"
  , ""
  , "  // Track all registered tool names to avoid collisions"
  , "  var registeredNames = {};"
  , ""
  , "  // Build unique tool names: function-name only, with .deployment-prefix on collision"
  , "  function buildToolNames(fns) {"
  , "    var MAX = 60;"
  , "    // Group by sanitized function name to detect collisions"
  , "    var groups = {};"
  , "    fns.forEach(function(fn) {"
  , "      var key = sanitizeName(fn.name, MAX);"
  , "      if (!groups[key]) groups[key] = [];"
  , "      groups[key].push(fn);"
  , "    });"
  , "    var result = [];"
  , "    Object.keys(groups).forEach(function(key) {"
  , "      var group = groups[key];"
  , "      if (group.length === 1 && !registeredNames[key]) {"
  , "        result.push({ fn: group[0], toolName: key });"
  , "      } else {"
  , "        // Collision: find shortest unique deployment prefix for each"
  , "        var deps = group.map(function(fn) { return sanitizeName(fn.deployment, MAX); });"
  , "        group.forEach(function(fn, i) {"
  , "          var dep = deps[i];"
  , "          var others = deps.filter(function(_, j) { return j !== i; });"
  , "          // Find shortest prefix of dep that distinguishes from all others"
  , "          var prefixLen = 1;"
  , "          while (prefixLen < dep.length) {"
  , "            var prefix = dep.substring(0, prefixLen);"
  , "            var unique = others.every(function(o) { return o.substring(0, prefixLen) !== prefix; });"
  , "            if (unique) break;"
  , "            prefixLen++;"
  , "          }"
  , "          var suffix = '.' + dep.substring(0, prefixLen);"
  , "          var baseName = sanitizeName(fn.name, MAX - suffix.length);"
  , "          result.push({ fn: fn, toolName: baseName + suffix });"
  , "        });"
  , "      }"
  , "    });"
  , "    return result;"
  , "  }"
  , ""
  , "  // Single fetch: org-level openapi.json with server-side scope filtering"
  , "  var openApiUrl = baseUrl + '/openapi.json';"
  , "  if (scope) openApiUrl += '?scope=' + encodeURIComponent(scope);"
  , ""
  , "  doFetch(openApiUrl)"
  , "    .then(function(r) { if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })"
  , "    .then(function(data) {"
  , "      var allFns = (data.functions || []).map(function(fn) {"
  , "        return {"
  , "          deployment: fn.deployment,"
  , "          name: fn.name,"
  , "          description: fn.description || '',"
  , "          returnType: fn.returnType || 'unknown',"
  , "          section: fn.section || null,"
  , "          isDeontic: fn.isDeontic || false,"
  , "          parameters: fn.parameters,"
  , "          parameterNames: Object.keys((fn.parameters && fn.parameters.properties) || {})"
  , "        };"
  , "      });"
  , ""
  , "      // Derive deployment list from functions"
  , "      var depMap = {};"
  , "      allFns.forEach(function(fn) {"
  , "        if (!depMap[fn.deployment]) depMap[fn.deployment] = { id: fn.deployment, status: 'ready' };"
  , "      });"
  , "      var deploymentInfos = Object.keys(depMap).map(function(k) { return depMap[k]; });"
  , ""
  , "      // Register tools"
  , "      var webmcpRegistered = false;"
  , "      if (typeof navigator !== 'undefined' && 'modelContext' in navigator) {"
  , "        var wantDiscovery = toolsMode === 'auto' || toolsMode === 'discovery' || toolsMode === 'all';"
  , "        var wantDirect = toolsMode === 'direct' || toolsMode === 'all' || (toolsMode === 'auto' && allFns.length <= 20);"
  , ""
  , "        if (wantDiscovery) registerDiscoveryTools(baseUrl, allFns);"
  , "        if (wantDirect) registerDirectTools(baseUrl, allFns);"
  , "        webmcpRegistered = true;"
  , "      }"
  , ""
  , "      window.dispatchEvent(new CustomEvent('webmcp-ready', {"
  , "        detail: { functions: allFns, deployments: deploymentInfos, webmcpRegistered: webmcpRegistered }"
  , "      }));"
  , "    })"
  , "    .catch(function(e) {"
  , "      console.error('WebMCP: failed to load deployments', e);"
  , "      window.dispatchEvent(new CustomEvent('webmcp-error', { detail: { error: e.message } }));"
  , "    });"
  , ""
  , "  function registerDiscoveryTools(baseUrl, fns) {"
  , "    var index = fns.map(function(fn) {"
  , "      return { deployment: fn.deployment, name: fn.name, description: fn.description, returnType: fn.returnType, section: fn.section, isDeontic: fn.isDeontic, parameterNames: fn.parameterNames };"
  , "    });"
  , ""
  , "    function regTool(def) { registeredNames[def.name] = true; navigator.modelContext.registerTool(def); }"
  , ""
  , "    regTool({"
  , "      name: 'search_rules',"
  , "      description: 'Search ' + fns.length + ' available legal rules by keyword. Returns matching deployment, name, description, return type, and parameter names.',"
  , "      inputSchema: { type: 'object', properties: { query: { type: 'string', description: 'Search keyword' } }, required: ['query'] },"
  , "      execute: function(args) {"
  , "        var words = (args.query || '').toLowerCase().split(/\\s+/).filter(Boolean);"
  , "        var matches = index.filter(function(fn) {"
  , "          var hay = (fn.name + ' ' + fn.description + ' ' + fn.deployment + ' ' + fn.parameterNames.join(' ')).toLowerCase();"
  , "          return words.every(function(w) { return hay.split(/\\s+/).some(function(t) { return t.indexOf(w) === 0 || w.indexOf(t) === 0; }); });"
  , "        });"
  , "        return { content: [{ type: 'text', text: JSON.stringify(matches, null, 2) }] };"
  , "      }"
  , "    });"
  , ""
  , "    regTool({"
  , "      name: 'get_rule_schema',"
  , "      description: 'Get the full parameter schema for a specific rule.',"
  , "      inputSchema: { type: 'object', properties: { deployment: { type: 'string', description: 'Deployment ID' }, function_name: { type: 'string', description: 'Function name' } }, required: ['deployment', 'function_name'] },"
  , "      execute: function(args) {"
  , "        return doFetch(baseUrl + '/deployments/' + encodeURIComponent(args.deployment) + '/functions/' + encodeURIComponent(args.function_name))"
  , "          .then(function(r) { return r.json(); })"
  , "          .then(function(data) { return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] }; });"
  , "      }"
  , "    });"
  , ""
  , "    regTool({"
  , "      name: 'evaluate_rule',"
  , "      description: 'Evaluate a legal rule with arguments. Use get_rule_schema first to understand required inputs.',"
  , "      inputSchema: { type: 'object', properties: { deployment: { type: 'string', description: 'Deployment ID' }, function_name: { type: 'string', description: 'Function name' }, arguments: { type: 'object', description: 'Key-value pairs matching the function parameters' } }, required: ['deployment', 'function_name', 'arguments'] },"
  , "      execute: function(args) {"
  , "        return doFetch(baseUrl + '/deployments/' + encodeURIComponent(args.deployment) + '/functions/' + encodeURIComponent(args.function_name) + '/evaluation', {"
  , "          method: 'POST',"
  , "          headers: { 'Content-Type': 'application/json' },"
  , "          body: JSON.stringify({ fnArguments: args.arguments })"
  , "        }).then(function(r) { return r.json(); })"
  , "          .then(function(data) { return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] }; });"
  , "      }"
  , "    });"
  , "  }"
  , ""
  , "  function registerDirectTools(baseUrl, fns) {"
  , "    var named = buildToolNames(fns);"
  , "    named.forEach(function(entry) {"
  , "      var fn = entry.fn;"
  , "      var sanitized = sanitizeParamsSchema(fn.parameters);"
  , "      registeredNames[entry.toolName] = true;"
  , "      navigator.modelContext.registerTool({"
  , "        name: entry.toolName,"
  , "        description: (fn.description || 'Evaluate ' + fn.name) + ' [' + fn.deployment + '/' + fn.name + ']',"
  , "        inputSchema: sanitized.schema,"
  , "        execute: function(args) {"
  , "          var originalArgs = remapArgs(args, sanitized.reverseMap);"
  , "          return doFetch(baseUrl + '/deployments/' + encodeURIComponent(fn.deployment) + '/functions/' + encodeURIComponent(fn.name) + '/evaluation', {"
  , "            method: 'POST',"
  , "            headers: { 'Content-Type': 'application/json' },"
  , "            body: JSON.stringify({ fnArguments: originalArgs })"
  , "          }).then(function(r) { return r.json(); })"
  , "            .then(function(data) { return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] }; });"
  , "        }"
  , "      });"
  , "    });"
  , "  }"
  , "})();"
  ]
