{-# LANGUAGE OverloadedStrings #-}

module WebMCPPage (
  RawHtml (..),
  RawJs (..),
  HTML,
  JavaScript,
  renderOrgWebMCPScript,
) where

import Data.ByteString.Lazy (ByteString)
import qualified Data.ByteString.Lazy.Char8 as LBS
import qualified Data.Text as Text
import qualified Data.Text.Encoding as Text.Encoding
import Network.HTTP.Media ((//), (/:))
import Servant (Accept (..), MimeRender (..))

-- | HTML content type for Servant.
data HTML

instance Accept HTML where
  contentType _ = "text" // "html" /: ("charset", "utf-8")

-- | JavaScript content type for Servant.
data JavaScript

instance Accept JavaScript where
  contentType _ = "application" // "javascript" /: ("charset", "utf-8")

-- | Raw HTML response.
newtype RawHtml = RawHtml { unRawHtml :: ByteString }

instance MimeRender HTML RawHtml where
  mimeRender _ (RawHtml bs) = bs

-- | Raw JavaScript response.
newtype RawJs = RawJs { unRawJs :: ByteString }

instance MimeRender JavaScript RawJs where
  mimeRender _ (RawJs bs) = bs

-- | Render the org-wide WebMCP JavaScript.
-- Fetches all deployments, applies scope filtering, registers tools.
-- Visibility flags control which tool categories are registered.
renderOrgWebMCPScript :: RawJs
renderOrgWebMCPScript = RawJs $ LBS.fromStrict $ Text.Encoding.encodeUtf8 $ Text.unlines
  [ "(function() {"
  , "  'use strict';"
  , ""
  , "  var scriptTag = document.currentScript || document.querySelector('script[src*=\"embed.js\"]');"
  , "  var apiKey = scriptTag && scriptTag.getAttribute('data-api-key');"
  , "  var scope = scriptTag && scriptTag.getAttribute('data-scope');"
  , "  // data-tools: comma-separated list of tool categories to register."
  , "  //   rules      — one tool per exported rule (direct evaluation)"
  , "  //   rule-tools — search_rules, get_rule_schema, evaluate_rule (discovery)"
  , "  //   file-tools — list_files, read_file, search_identifier, search_text"
  , "  //   auto       — rules (if ≤20) or rule-tools (default)"
  , "  //   all        — rules + rule-tools + file-tools"
  , "  var toolsAttr = (scriptTag && scriptTag.getAttribute('data-tools')) || 'auto';"
  , "  var toolsSet = toolsAttr.split(',').map(function(s) { return s.trim().toLowerCase(); });"
  , "  function wantTool(name) { return toolsSet.indexOf(name) >= 0; }"
  , "  var isAuto = wantTool('auto');"
  , "  var isAll = wantTool('all');"
  , "  var baseUrl = scriptTag && scriptTag.src ? new URL(scriptTag.src).origin : window.location.origin;"
  , ""
  , "  var authHeaders = apiKey ? { 'Authorization': 'Bearer ' + apiKey } : {};"
  , "  var fetchOpts = apiKey ? {} : { credentials: 'include' };"
  , ""
  , "  function doFetch(url, opts) {"
  , "    return fetch(url, Object.assign({}, fetchOpts, { headers: Object.assign({}, authHeaders, (opts && opts.headers) || {}) }, opts || {}));"
  , "  }"
  , ""
  , ""
  , "  function sanitizeName(name, maxLen) {"
  , "    var s = name.replace(/[^a-zA-Z0-9_.-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');"
  , "    if (!s || !/^[a-zA-Z_]/.test(s)) s = '_' + s;"
  , "    return s.substring(0, maxLen || 60);"
  , "  }"
  , ""
  , "  // Sanitize a property name: same replacement char (-) as sanitizeName"
  , "  function sanitizePropName(name) {"
  , "    var s = name.replace(/[^a-zA-Z0-9_.-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');"
  , "    return s || '_unnamed';"
  , "  }"
  , ""
  , "  // Sanitize all property names in a parameters schema and return"
  , "  // { schema, reverseMap } where reverseMap maps sanitized -> original"
  , "  // The reverseMap includes all nested property names recursively."
  , "  function sanitizeParamsSchema(params) {"
  , "    if (!params || !params.properties) return { schema: params || { type: 'object', properties: {}, required: [] }, reverseMap: {} };"
  , "    var newProps = {}, reverseMap = {};"
  , "    Object.keys(params.properties).forEach(function(origKey) {"
  , "      var safKey = sanitizePropName(origKey);"
  , "      newProps[safKey] = sanitizeParamValue(params.properties[origKey], reverseMap);"
  , "      if (safKey !== origKey) reverseMap[safKey] = origKey;"
  , "    });"
  , "    var newRequired = (params.required || []).map(sanitizePropName);"
  , "    return {"
  , "      schema: { type: 'object', properties: newProps, required: newRequired },"
  , "      reverseMap: reverseMap"
  , "    };"
  , "  }"
  , ""
  , "  // Recursively sanitize nested property names inside a parameter value."
  , "  // Accumulates sanitized -> original mappings into reverseMap."
  , "  // Produces JSON Schema draft 2020-12 compliant output (no alias/propertyOrder)."
  , "  function sanitizeParamValue(p, reverseMap) {"
  , "    if (!p) return p;"
  , "    var out = { type: p.type, description: p.description };"
  , "    if (p['enum'] && p['enum'].length) out['enum'] = p['enum'];"
  , "    if (p.format) out.format = p.format;"
  , "    if (p.properties) {"
  , "      var nested = {};"
  , "      Object.keys(p.properties).forEach(function(k) {"
  , "        var safKey = sanitizePropName(k);"
  , "        nested[safKey] = sanitizeParamValue(p.properties[k], reverseMap);"
  , "        if (safKey !== k) reverseMap[safKey] = k;"
  , "      });"
  , "      out.properties = nested;"
  , "    } else if (p.type === 'object') { out.properties = {}; }"
  , "    if (p.items) out.items = sanitizeParamValue(p.items, reverseMap);"
  , "    return out;"
  , "  }"
  , ""
  , "  // Remap sanitized argument keys back to original L4 names."
  , "  // Recursively remaps keys in nested objects and arrays."
  , "  function remapArgs(args, reverseMap) {"
  , "    if (Array.isArray(args)) return args.map(function(v) { return remapArgs(v, reverseMap); });"
  , "    if (args && typeof args === 'object') {"
  , "      var out = {};"
  , "      Object.keys(args).forEach(function(k) {"
  , "        out[reverseMap[k] || k] = remapArgs(args[k], reverseMap);"
  , "      });"
  , "      return out;"
  , "    }"
  , "    return args;"
  , "  }"
  , ""
  , "  // Replace original L4 field names with their sanitized equivalents in text."
  , "  // reverseMap is sanitized->original; we invert it for text replacement."
  , "  function sanitizeErrorText(text, reverseMap) {"
  , "    var result = text;"
  , "    Object.keys(reverseMap).forEach(function(sanitized) {"
  , "      var original = reverseMap[sanitized];"
  , "      if (original !== sanitized) result = result.split(original).join(sanitized);"
  , "    });"
  , "    return result;"
  , "  }"
  , ""
  , "  // Track all registered tool names to avoid collisions"
  , "  var registeredNames = {};"
  , ""
  , "  // Build unique tool names: function-name only, with .deployment-prefix on collision"
  , "  function buildToolNames(fns) {"
  , "    var MAX = 60;"
  , "    // Group by sanitized function name to detect collisions"
  , "    var groups = {};"
  , "    fns.forEach(function(fn) {"
  , "      var key = sanitizeName(fn.name, MAX);"
  , "      if (!groups[key]) groups[key] = [];"
  , "      groups[key].push(fn);"
  , "    });"
  , "    var result = [];"
  , "    Object.keys(groups).forEach(function(key) {"
  , "      var group = groups[key];"
  , "      if (group.length === 1 && !registeredNames[key]) {"
  , "        result.push({ fn: group[0], toolName: key });"
  , "      } else {"
  , "        // Collision: find shortest unique deployment prefix for each"
  , "        var deps = group.map(function(fn) { return sanitizeName(fn.deployment, MAX); });"
  , "        group.forEach(function(fn, i) {"
  , "          var dep = deps[i];"
  , "          var others = deps.filter(function(_, j) { return j !== i; });"
  , "          // Find shortest prefix of dep that distinguishes from all others"
  , "          var prefixLen = 1;"
  , "          while (prefixLen < dep.length) {"
  , "            var prefix = dep.substring(0, prefixLen);"
  , "            var unique = others.every(function(o) { return o.substring(0, prefixLen) !== prefix; });"
  , "            if (unique) break;"
  , "            prefixLen++;"
  , "          }"
  , "          var suffix = '.' + dep.substring(0, prefixLen);"
  , "          var baseName = sanitizeName(fn.name, MAX - suffix.length);"
  , "          result.push({ fn: fn, toolName: baseName + suffix });"
  , "        });"
  , "      }"
  , "    });"
  , "    return result;"
  , "  }"
  , ""
  , "  // Fetch deployments with full function details"
  , "  var deploymentsUrl = baseUrl + '/deployments?functions=full';"
  , "  if (scope) deploymentsUrl += '&scope=' + encodeURIComponent(scope);"
  , ""
  , "  doFetch(deploymentsUrl)"
  , "    .then(function(r) { if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })"
  , "    .then(function(deployments) {"
  , "      // Extract functions from deployment metadata"
  , "      var allFns = [];"
  , "      var hasFiles = false;"
  , "      var deploymentInfos = [];"
  , "      deployments.forEach(function(dep) {"
  , "        if (dep.status === 'failed' || !dep.metadata) return;"
  , "        deploymentInfos.push({ id: dep.id, status: dep.status });"
  , "        if (dep.metadata.files) hasFiles = true;"
  , "        (dep.metadata.functions || []).forEach(function(fn) {"
  , "          allFns.push({"
  , "            deployment: dep.id,"
  , "            name: fn.name,"
  , "            description: fn.description || '',"
  , "            returnType: fn.returnType || 'unknown',"
  , "            section: fn.section || null,"
  , "            parameters: fn.parameters,"
  , "            parameterNames: Object.keys((fn.parameters && fn.parameters.properties) || {})"
  , "          });"
  , "        });"
  , "      });"
  , ""
  , "      // Register tools based on what's available in the data"
  , "      var webmcpRegistered = false;"
  , "      if (typeof navigator !== 'undefined' && 'modelContext' in navigator) {"
  , "        var wantRuleTools = isAll || wantTool('rule-tools') || (isAuto && allFns.length > 20);"
  , "        var wantRules = isAll || wantTool('rules') || (isAuto && allFns.length <= 20);"
  , "        var wantFileTools = isAll || wantTool('file-tools');"
  , ""
  , "        if (wantRuleTools && allFns.length > 0) registerDiscoveryTools(baseUrl, allFns, hasFiles && wantFileTools);"
  , "        if (wantRules && allFns.length > 0) registerDirectTools(baseUrl, allFns);"
  , "        if (wantFileTools && hasFiles) registerFileTools(baseUrl, deployments);"
  , "        webmcpRegistered = true;"
  , "      }"
  , ""
  , "      window.dispatchEvent(new CustomEvent('webmcp-ready', {"
  , "        detail: { functions: allFns, deployments: deploymentInfos, webmcpRegistered: webmcpRegistered }"
  , "      }));"
  , "    })"
  , "    .catch(function(e) {"
  , "      console.error('WebMCP: failed to load deployments', e);"
  , "      window.dispatchEvent(new CustomEvent('webmcp-error', { detail: { error: e.message } }));"
  , "    });"
  , ""
  , "  function registerDiscoveryTools(baseUrl, fns, hasFiles) {"
  , "    var index = fns.map(function(fn) {"
  , "      return { deployment: fn.deployment, name: fn.name, description: fn.description, returnType: fn.returnType, section: fn.section, parameterNames: fn.parameterNames };"
  , "    });"
  , ""
  , "    function regTool(def) { registeredNames[def.name] = true; navigator.modelContext.registerTool(def); }"
  , ""
  , "    regTool({"
  , "      name: 'search_rules',"
  , "      description: 'Tooling: Search ' + fns.length + ' available legal rules by keyword. Returns matching deployment, name, description, return type, and parameter names.',"
  , "      inputSchema: { type: 'object', properties: { query: { type: 'string', description: 'Search keyword' } }, required: ['query'] },"
  , "      execute: function(args) {"
  , "        var words = (args.query || '').toLowerCase().split(/\\s+/).filter(Boolean);"
  , "        var matches = index.filter(function(fn) {"
  , "          var hay = (fn.name + ' ' + fn.description + ' ' + fn.deployment + ' ' + fn.parameterNames.join(' ')).toLowerCase();"
  , "          return words.every(function(w) { return hay.split(/\\s+/).some(function(t) { return t.indexOf(w) === 0 || w.indexOf(t) === 0; }); });"
  , "        });"
  , "        return { content: [{ type: 'text', text: JSON.stringify(matches, null, 2) }] };"
  , "      }"
  , "    });"
  , ""
  , "    regTool({"
  , "      name: 'get_rule_schema',"
  , "      description: 'Tooling: Get the full parameter schema for a specific rule.',"
  , "      inputSchema: { type: 'object', properties: { deployment: { type: 'string', description: 'Deployment ID' }, function_name: { type: 'string', description: 'Function name' } }, required: ['deployment', 'function_name'] },"
  , "      execute: function(args) {"
  , "        return doFetch(baseUrl + '/deployments/' + encodeURIComponent(args.deployment) + '/functions/' + encodeURIComponent(args.function_name))"
  , "          .then(function(r) { return r.json(); })"
  , "          .then(function(data) { return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] }; });"
  , "      }"
  , "    });"
  , ""
  , "    regTool({"
  , "      name: 'evaluate_rule',"
  , "      description: 'Tooling: Evaluate a legal rule with arguments. Use get_rule_schema first to understand required inputs. For DEONTIC rules, also pass startTime (number) and events (array of {party, action, at}).',"
  , "      inputSchema: { type: 'object', properties: { deployment: { type: 'string', description: 'Deployment ID' }, function_name: { type: 'string', description: 'Function name' }, arguments: { type: 'object', description: 'Key-value pairs matching the function parameters' }, startTime: { type: 'number', description: 'Start time for DEONTIC contract simulation' }, events: { type: 'array', description: 'Events for DEONTIC contract simulation', items: { type: 'object' } } }, required: ['deployment', 'function_name', 'arguments'] },"
  , "      execute: function(args) {"
  , "        var body = { arguments: args.arguments };"
  , "        if (args.startTime !== undefined) body.startTime = args.startTime;"
  , "        if (args.events !== undefined) body.events = args.events;"
  , "        return doFetch(baseUrl + '/deployments/' + encodeURIComponent(args.deployment) + '/functions/' + encodeURIComponent(args.function_name) + '/evaluation', {"
  , "          method: 'POST',"
  , "          headers: { 'Content-Type': 'application/json' },"
  , "          body: JSON.stringify(body)"
  , "        }).then(function(r) { return r.json(); })"
  , "          .then(function(data) { return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] }; });"
  , "      }"
  , "    });"
  , "  }"
  , ""
  , "  function registerFileTools(baseUrl, deployments) {"
  , "    function regTool(def) { registeredNames[def.name] = true; navigator.modelContext.registerTool(def); }"
  , ""
  , "    regTool({"
  , "      name: 'list_files',"
  , "      description: 'Tooling: List .l4 files and their exports in a deployment',"
  , "      inputSchema: { type: 'object', properties: { deployment: { type: 'string', description: 'Omit for all deployments' } } },"
  , "      execute: function(args) {"
  , "        if (args.deployment) {"
  , "          return doFetch(baseUrl + '/deployments/' + encodeURIComponent(args.deployment) + '/files')"
  , "            .then(function(r) { return r.json(); })"
  , "            .then(function(data) { return { content: [{ type: 'text', text: JSON.stringify(data.files || [], null, 2) }] }; });"
  , "        }"
  , "        var allFiles = [];"
  , "        deployments.forEach(function(dep) {"
  , "          if (dep.metadata && dep.metadata.files) {"
  , "            dep.metadata.files.forEach(function(f) { allFiles.push({ deployment: dep.id, path: f.path, exports: f.exports }); });"
  , "          }"
  , "        });"
  , "        return { content: [{ type: 'text', text: JSON.stringify(allFiles, null, 2) }] };"
  , "      }"
  , "    });"
  , ""
  , "    regTool({"
  , "      name: 'read_file',"
  , "      description: 'Tooling: Read .l4 source file content, optionally a line range',"
  , "      inputSchema: { type: 'object', properties: { deployment: { type: 'string' }, path: { type: 'string', description: 'e.g. rules/main.l4' }, lines: { type: 'string', description: 'start:end (e.g. 85:89)' } }, required: ['deployment', 'path'] },"
  , "      execute: function(args) {"
  , "        var url = baseUrl + '/deployments/' + encodeURIComponent(args.deployment) + '/files/' + args.path;"
  , "        if (args.lines) url += '?lines=' + encodeURIComponent(args.lines);"
  , "        return doFetch(url).then(function(r) { return r.text(); })"
  , "          .then(function(text) { return { content: [{ type: 'text', text: text }] }; });"
  , "      }"
  , "    });"
  , ""
  , "    regTool({"
  , "      name: 'search_identifier',"
  , "      description: 'Tooling: Find definitions and references of an L4 identifier. Text-based, may match in comments.',"
  , "      inputSchema: { type: 'object', properties: { identifier: { type: 'string' }, deployment: { type: 'string', description: 'Omit for all deployments' }, file: { type: 'string', description: 'Scope to one file' } }, required: ['identifier'] },"
  , "      execute: function(args) {"
  , "        var dep = args.deployment || (deployments[0] && deployments[0].id) || '';"
  , "        var url = baseUrl + '/deployments/' + encodeURIComponent(dep) + '/files?identifier=' + encodeURIComponent(args.identifier);"
  , "        if (args.file) url += '&file=' + encodeURIComponent(args.file);"
  , "        return doFetch(url).then(function(r) { return r.json(); })"
  , "          .then(function(data) { return { content: [{ type: 'text', text: JSON.stringify(data.matches || [], null, 2) }] }; });"
  , "      }"
  , "    });"
  , ""
  , "    regTool({"
  , "      name: 'search_text',"
  , "      description: 'Tooling: Search text in .l4 source files (case-insensitive)',"
  , "      inputSchema: { type: 'object', properties: { query: { type: 'string' }, deployment: { type: 'string', description: 'Omit for all deployments' }, file: { type: 'string', description: 'Scope to one file' } }, required: ['query'] },"
  , "      execute: function(args) {"
  , "        var dep = args.deployment || (deployments[0] && deployments[0].id) || '';"
  , "        var url = baseUrl + '/deployments/' + encodeURIComponent(dep) + '/files?search=' + encodeURIComponent(args.query);"
  , "        if (args.file) url += '&file=' + encodeURIComponent(args.file);"
  , "        return doFetch(url).then(function(r) { return r.json(); })"
  , "          .then(function(data) { return { content: [{ type: 'text', text: JSON.stringify(data.matches || [], null, 2) }] }; });"
  , "      }"
  , "    });"
  , "  }"
  , ""
  , "  function registerDirectTools(baseUrl, fns) {"
  , "    var named = buildToolNames(fns);"
  , "    named.forEach(function(entry) {"
  , "      var fn = entry.fn;"
  , "      var sanitized = sanitizeParamsSchema(fn.parameters);"
  , "      registeredNames[entry.toolName] = true;"
  , "      navigator.modelContext.registerTool({"
  , "        name: entry.toolName,"
  , "        description: 'L4 Rule: ' + (fn.description || fn.name) + ' [' + fn.deployment + '/' + fn.name + ']',"
  , "        inputSchema: (fn.returnType || '').startsWith('DEONTIC') ? { type: 'object', properties: { arguments: sanitized.schema, startTime: { type: 'number', description: 'Start time for contract simulation' }, events: { type: 'array', description: 'Events for contract simulation (each: {party, action, at})', items: { type: 'object' } } }, required: ['arguments', 'startTime', 'events'] } : sanitized.schema,"
  , "        execute: function(args) {"
  , "          var originalArgs = (fn.returnType || '').startsWith('DEONTIC') ? remapArgs(args.arguments || {}, sanitized.reverseMap) : remapArgs(args, sanitized.reverseMap);"
  , "          var body = { arguments: originalArgs };"
  , "          if ((fn.returnType || '').startsWith('DEONTIC')) { body.startTime = args.startTime; body.events = args.events; }"
  , "          return doFetch(baseUrl + '/deployments/' + encodeURIComponent(fn.deployment) + '/functions/' + encodeURIComponent(fn.name) + '/evaluation', {"
  , "            method: 'POST',"
  , "            headers: { 'Content-Type': 'application/json' },"
  , "            body: JSON.stringify(body)"
  , "          }).then(function(r) { return r.json(); })"
  , "            .then(function(data) {"
  , "              var text = sanitizeErrorText(JSON.stringify(data, null, 2), sanitized.reverseMap);"
  , "              return { content: [{ type: 'text', text: text }] };"
  , "            });"
  , "        }"
  , "      });"
  , "    });"
  , "  }"
  , "})();"
  ]
