// Install a deployment's plugin bundle locally — into Claude Code's
// `~/.claude/skills/{name}/` (plus `~/.claude.json` mcpServers) or into
// VS Code's user-level `mcp.json`. Triggered by the sidebar Integrate
// popover's "Add to …" buttons.
//
// The bundle itself is generated by the auth-proxy at
// `mcp.legalese.cloud/{slug}/{deploymentId}/.plugin` (the Claude Code
// plugin zip; the sibling `.skill` route is the skills-CLI discovery
// surface). We download the zip with the user's session token, parse it
// (STORE-only — the auth-proxy always writes uncompressed entries), and
// write the relevant files for the chosen target.

import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import * as vscode from 'vscode'
import type { AuthManager } from './auth.js'
import type { ServiceClient } from './service-client.js'
import { showTimedInformationMessage } from './notifications.js'

export type InstallTarget = 'claude-code' | 'vscode-chat' | 'download-zip'

export interface InstallDeploymentSkillOptions {
  deploymentId: string
  target: InstallTarget
  auth: AuthManager
  serviceClient: ServiceClient
  outputChannel: vscode.OutputChannel
  /** VS Code user-data path (the one containing `mcp.json`). Required
   *  for the `vscode-chat` target; derived from
   *  `context.globalStorageUri` by the caller. */
  userDataPath: string | undefined
}

/**
 * Entry point dispatched from the sidebar messenger.
 */
export async function installDeploymentSkill(
  opts: InstallDeploymentSkillOptions
): Promise<void> {
  const { deploymentId, target, auth, serviceClient, outputChannel } = opts

  const slug = auth.getCloudOrgSlug()
  if (!slug) {
    void vscode.window.showWarningMessage(
      'Sign in with Legalese Cloud to install a deployment plugin.'
    )
    return
  }

  const bundleName = `${slug}-${deploymentId}`
  const mcpUrl = `https://mcp.legalese.cloud/${slug}/${encodeURIComponent(
    deploymentId
  )}`

  let zip: Buffer
  try {
    zip = await serviceClient.getDeploymentSkillBundle(deploymentId)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    outputChannel.appendLine(`[install] Download failed: ${msg}`)
    // The 422 case (missing Intended use) is the only failure the user
    // can act on — surface it directly so they know to edit metadata.
    if (msg.includes('422') || /Intended use/i.test(msg)) {
      void vscode.window.showErrorMessage(
        `Add an "Intended use" description to ${deploymentId} before installing it as a plugin.`
      )
    } else {
      void vscode.window.showErrorMessage(
        `Could not download plugin bundle: ${msg}`
      )
    }
    return
  }

  if (target === 'download-zip') {
    await saveZipToDisk(bundleName, zip, outputChannel)
    return
  }

  const entries = parseStoreZip(zip)

  if (target === 'claude-code') {
    await installClaudeCode(bundleName, mcpUrl, entries, outputChannel)
  } else {
    installVscodeChat(
      bundleName,
      mcpUrl,
      entries,
      opts.userDataPath,
      outputChannel
    )
  }
}

// ---------------------------------------------------------------------------
// Download-to-disk: prompt the user for a save location and write the raw
// zip there. Useful for distributing the plugin (e.g. to a teammate's
// `claude --plugin-url file://…` install) or for inspecting the bundle.
// ---------------------------------------------------------------------------

async function saveZipToDisk(
  bundleName: string,
  zip: Buffer,
  outputChannel: vscode.OutputChannel
): Promise<void> {
  const defaultUri = vscode.Uri.file(
    path.join(os.homedir(), 'Downloads', `${bundleName}.zip`)
  )
  const target = await vscode.window.showSaveDialog({
    defaultUri,
    filters: { 'Zip Archive': ['zip'] },
    saveLabel: 'Save plugin',
    title: `Save ${bundleName}.zip`,
  })
  if (!target) return // user cancelled — no toast, no log spam

  try {
    fs.mkdirSync(path.dirname(target.fsPath), { recursive: true })
    fs.writeFileSync(target.fsPath, zip)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    outputChannel.appendLine(`[install] Failed to save zip: ${msg}`)
    void vscode.window.showErrorMessage(`Could not save plugin zip: ${msg}`)
    return
  }

  outputChannel.appendLine(
    `[install] Saved ${zip.length}B plugin zip to ${target.fsPath}`
  )
  void vscode.window.showInformationMessage(
    `Saved ${bundleName}.zip to ${target.fsPath}.`,
    'Okay'
  )
}

// ---------------------------------------------------------------------------
// Shared: drop the SKILL.md + references at `~/.claude/skills/{name}/`.
//
// VS Code Chat reads agent skills from `~/.claude/skills/` natively (along
// with `~/.copilot/skills/` and `~/.agents/skills/`) per the Agent Skills
// spec at agentskills.io. Claude Code reads the same path. Using one
// canonical location means installing for one target then the other does
// not duplicate the skill folder.
// ---------------------------------------------------------------------------

function writeSkillFolder(
  bundleName: string,
  entries: ReadonlyArray<ZipEntry>,
  outputChannel: vscode.OutputChannel
): void {
  const skillsRoot = path.join(os.homedir(), '.claude', 'skills', bundleName)

  // The bundle's skill content lives at
  // `{bundleName}/skills/{bundleName}/...`. Strip that prefix so files
  // land at `~/.claude/skills/{bundleName}/...` (matching the layout
  // both Claude Code and VS Code Chat expect for an installed skill).
  const skillPrefix = `${bundleName}/skills/${bundleName}/`
  let wrote = 0
  for (const e of entries) {
    if (!e.name.startsWith(skillPrefix)) continue
    const rel = e.name.slice(skillPrefix.length)
    if (!rel) continue
    const dest = path.join(skillsRoot, rel)
    // Belt-and-braces guard: refuse to escape the skill root even if
    // the zip somehow contains '..' segments.
    const resolved = path.resolve(dest)
    if (!resolved.startsWith(path.resolve(skillsRoot) + path.sep)) {
      outputChannel.appendLine(`[install] Refused unsafe entry path: ${e.name}`)
      continue
    }
    fs.mkdirSync(path.dirname(resolved), { recursive: true })
    fs.writeFileSync(resolved, e.content)
    wrote++
  }
  outputChannel.appendLine(
    `[install] Wrote ${wrote} skill file${wrote === 1 ? '' : 's'} to ${skillsRoot}`
  )
}

// ---------------------------------------------------------------------------
// Claude Code: write the skill folder + ~/.claude.json mcpServers entry.
// ---------------------------------------------------------------------------

async function installClaudeCode(
  bundleName: string,
  mcpUrl: string,
  entries: ReadonlyArray<ZipEntry>,
  outputChannel: vscode.OutputChannel
): Promise<void> {
  const claudeConfigPath = path.join(os.homedir(), '.claude.json')

  // Don't try to register the MCP server if Claude Code isn't installed —
  // matches the existing addL4ToolsToClaudeCode gate. Skill files are
  // skipped too in this case (the user explicitly chose "Claude Code"
  // and got told it's missing; writing orphan files would be confusing).
  try {
    fs.accessSync(claudeConfigPath, fs.constants.R_OK)
  } catch {
    void vscode.window.showWarningMessage(
      'Claude Code .claude.json was not found in your home directory. Install Claude Code first, then try again.'
    )
    return
  }

  writeSkillFolder(bundleName, entries, outputChannel)

  // mcpServers entry — point Claude Code at the hosted endpoint. The
  // single OAuth Resource Indicator means the user OAuths once for
  // `https://mcp.legalese.cloud` and all per-deployment entries share
  // the token thereafter.
  try {
    const raw = fs.readFileSync(claudeConfigPath, 'utf-8')
    const config = JSON.parse(raw)
    if (!config.mcpServers) config.mcpServers = {}
    const existing = config.mcpServers[bundleName]
    const desired = { type: 'http', url: mcpUrl }
    const same =
      existing && existing.type === desired.type && existing.url === desired.url
    if (!same) {
      config.mcpServers[bundleName] = { ...(existing ?? {}), ...desired }
      fs.writeFileSync(claudeConfigPath, JSON.stringify(config, null, 2))
      outputChannel.appendLine(
        existing
          ? `[install] Refreshed ${bundleName} in ~/.claude.json`
          : `[install] Added ${bundleName} to ~/.claude.json`
      )
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    outputChannel.appendLine(
      `[install] Failed to update ~/.claude.json: ${msg}`
    )
    void vscode.window.showErrorMessage(
      `Wrote skill files but could not update ~/.claude.json: ${msg}`
    )
    return
  }

  void vscode.window.showInformationMessage(
    `Installed ${bundleName} to Claude Code. Restart Claude Code to pick it up.`,
    'Okay'
  )
}

// ---------------------------------------------------------------------------
// VS Code Chat: write the skill folder (VS Code reads `~/.claude/skills/`
// natively per the Agent Skills spec) AND the per-deployment MCP entry
// into the user-level mcp.json. Both surfaces — name+description skill
// matching and direct MCP tool access — are wired up by this single
// install.
// ---------------------------------------------------------------------------

function installVscodeChat(
  bundleName: string,
  mcpUrl: string,
  entries: ReadonlyArray<ZipEntry>,
  userDataPath: string | undefined,
  outputChannel: vscode.OutputChannel
): void {
  if (!userDataPath) {
    outputChannel.appendLine(
      `[install] Skipped VS Code mcp.json update: userDataPath not available`
    )
    void vscode.window.showErrorMessage(
      "Couldn't locate VS Code's mcp.json. Install manually by adding the MCP server URL to your settings."
    )
    return
  }

  writeSkillFolder(bundleName, entries, outputChannel)

  const mcpJsonPath = path.join(userDataPath, 'mcp.json')
  const desired = { type: 'http', url: mcpUrl }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let config: any = {}
  try {
    const raw = fs.readFileSync(mcpJsonPath, 'utf-8')
    if (raw.trim()) {
      try {
        config = JSON.parse(raw)
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err)
        outputChannel.appendLine(
          `[install] Skipped ${mcpJsonPath}: not valid JSON (${msg}). Remove comments or add the entry manually.`
        )
        void vscode.window.showErrorMessage(
          'VS Code mcp.json could not be parsed as JSON. Add the MCP server URL manually.'
        )
        return
      }
    }
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
      const msg = err instanceof Error ? err.message : String(err)
      outputChannel.appendLine(
        `[install] Failed to read ${mcpJsonPath}: ${msg}`
      )
      void vscode.window.showErrorMessage(
        `Could not read VS Code mcp.json: ${msg}`
      )
      return
    }
    // ENOENT → fall through and create.
  }

  if (!config || typeof config !== 'object') config = {}
  if (!config.servers || typeof config.servers !== 'object') {
    config.servers = {}
  }

  const existing = config.servers[bundleName]
  if (
    existing &&
    existing.type === desired.type &&
    existing.url === desired.url
  ) {
    showTimedInformationMessage(
      `${bundleName} already configured in VS Code Chat.`
    )
    return
  }

  config.servers[bundleName] = { ...(existing ?? {}), ...desired }

  try {
    fs.mkdirSync(path.dirname(mcpJsonPath), { recursive: true })
    fs.writeFileSync(mcpJsonPath, JSON.stringify(config, null, 2) + '\n')
    outputChannel.appendLine(
      existing
        ? `[install] Refreshed ${bundleName} in ${mcpJsonPath}`
        : `[install] Added ${bundleName} to ${mcpJsonPath}`
    )
    void vscode.window.showInformationMessage(
      `Installed ${bundleName} for VS Code Chat (skill + MCP server). Reload the window to pick it up.`,
      'Okay'
    )
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    outputChannel.appendLine(`[install] Failed to write ${mcpJsonPath}: ${msg}`)
    void vscode.window.showErrorMessage(
      `Could not write VS Code mcp.json: ${msg}`
    )
  }
}

// ---------------------------------------------------------------------------
// Minimal STORE-only ZIP parser.
//
// The auth-proxy always writes uncompressed entries (method=0, gp-flag=0)
// so we don't need DEFLATE, encryption, or Zip64 support. We walk local
// file headers from the start and stop at the central directory
// signature. Anything more exotic in the input is a server-side bug.
// ---------------------------------------------------------------------------

interface ZipEntry {
  name: string
  content: Buffer
}

const LOCAL_FILE_HEADER = 0x04034b50
const CENTRAL_DIR_HEADER = 0x02014b50

function parseStoreZip(buf: Buffer): ZipEntry[] {
  const entries: ZipEntry[] = []
  let off = 0
  while (off + 30 <= buf.length) {
    const sig = buf.readUInt32LE(off)
    if (sig === CENTRAL_DIR_HEADER) break
    if (sig !== LOCAL_FILE_HEADER) {
      throw new Error(
        `Unexpected ZIP signature 0x${sig.toString(16)} at offset ${off}`
      )
    }
    const method = buf.readUInt16LE(off + 8)
    if (method !== 0) {
      throw new Error(`Unsupported compression method ${method} in plugin zip`)
    }
    const compressed = buf.readUInt32LE(off + 18)
    const nameLen = buf.readUInt16LE(off + 26)
    const extraLen = buf.readUInt16LE(off + 28)
    const nameStart = off + 30
    const dataStart = nameStart + nameLen + extraLen
    const name = buf.slice(nameStart, nameStart + nameLen).toString('utf-8')
    const content = buf.slice(dataStart, dataStart + compressed)
    entries.push({ name, content })
    off = dataStart + compressed
  }
  return entries
}
