// Install a deployment's plugin bundle locally into a chosen AI harness.
//
// The bundle is generated by the auth-proxy at
// `mcp.legalese.cloud/{slug}/{deploymentId}/.plugin` (a Claude Code plugin
// zip). We download it with the user's session token, parse it (STORE-only —
// the auth-proxy always writes uncompressed entries), drop the SKILL.md
// folder for harnesses that read agent skills, and write the per-deployment
// MCP server entry into the harness's config (see `harness-config.ts`).
// Triggered by the sidebar Integrate popover's "Install as Skill" menu.

import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import * as vscode from 'vscode'
import type { AuthManager } from './auth.js'
import type { ServiceClient } from './service-client.js'
import type { Harness } from 'jl4-client-rpc'
import { writeHarnessMcp, announce, type HarnessCtx } from './harness-config.js'

/** `download-zip` saves the raw bundle; every other target installs into that
 *  harness's config (and, where the harness reads agent skills, the SKILL.md
 *  folder too). */
export type InstallTarget = Harness | 'download-zip'

export interface InstallDeploymentSkillOptions {
  deploymentId: string
  target: InstallTarget
  auth: AuthManager
  serviceClient: ServiceClient
  outputChannel: vscode.OutputChannel
  /** VS Code user-data path (contains `mcp.json` + `globalStorage/`).
   *  Required for the vscode/cline targets; derived from
   *  `context.globalStorageUri` by the caller. */
  userDataPath: string | undefined
}

// Harnesses that read agent skills from ~/.claude/skills (per agentskills.io).
// For these we also drop the SKILL.md folder; the rest are MCP-only.
function readsAgentSkills(target: Harness): boolean {
  return target === 'claude-code' || target === 'vscode'
}

/**
 * Entry point dispatched from the sidebar messenger.
 */
export async function installDeploymentSkill(
  opts: InstallDeploymentSkillOptions
): Promise<void> {
  const { deploymentId, target, auth, serviceClient, outputChannel } = opts

  const slug = auth.getCloudOrgSlug()
  if (!slug) {
    void vscode.window.showWarningMessage(
      'Sign in with Legalese Cloud to install a deployment.'
    )
    return
  }

  const bundleName = `${slug}-${deploymentId}`
  const mcpUrl = `https://mcp.legalese.cloud/${slug}/${encodeURIComponent(
    deploymentId
  )}`
  const ctx: HarnessCtx = { userDataPath: opts.userDataPath, outputChannel }

  if (target === 'download-zip') {
    const zip = await downloadBundle(deploymentId, serviceClient, outputChannel)
    if (zip) await saveZipToDisk(bundleName, zip, outputChannel)
    return
  }

  // Drop the skill folder for harnesses that read agent skills natively.
  if (readsAgentSkills(target)) {
    const zip = await downloadBundle(deploymentId, serviceClient, outputChannel)
    if (!zip) return
    writeSkillFolder(bundleName, parseStoreZip(zip), outputChannel)
  }

  const res = writeHarnessMcp(target, bundleName, mcpUrl, ctx)
  announce(target, deploymentId, res)
}

/**
 * Download the deployment's plugin bundle, surfacing the actionable 422
 * (missing Intended use) case. Returns null on failure (already toasted).
 */
async function downloadBundle(
  deploymentId: string,
  serviceClient: ServiceClient,
  outputChannel: vscode.OutputChannel
): Promise<Buffer | null> {
  try {
    return await serviceClient.getDeploymentSkillBundle(deploymentId)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    outputChannel.appendLine(`[install] Download failed: ${msg}`)
    // The 422 case (missing Intended use) is the only failure the user can
    // act on — surface it directly so they know to edit metadata.
    if (msg.includes('422') || /Intended use/i.test(msg)) {
      void vscode.window.showErrorMessage(
        `Add an "Intended use" description to ${deploymentId} before installing it.`
      )
    } else {
      void vscode.window.showErrorMessage(
        `Could not download plugin bundle: ${msg}`
      )
    }
    return null
  }
}

// ---------------------------------------------------------------------------
// Download-to-disk: prompt the user for a save location and write the raw
// zip there. Useful for distributing the plugin or inspecting the bundle.
// ---------------------------------------------------------------------------

async function saveZipToDisk(
  bundleName: string,
  zip: Buffer,
  outputChannel: vscode.OutputChannel
): Promise<void> {
  const defaultUri = vscode.Uri.file(
    path.join(os.homedir(), 'Downloads', `${bundleName}.zip`)
  )
  const target = await vscode.window.showSaveDialog({
    defaultUri,
    filters: { 'Zip Archive': ['zip'] },
    saveLabel: 'Save plugin',
    title: `Save ${bundleName}.zip`,
  })
  if (!target) return // user cancelled — no toast, no log spam

  try {
    fs.mkdirSync(path.dirname(target.fsPath), { recursive: true })
    fs.writeFileSync(target.fsPath, zip)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    outputChannel.appendLine(`[install] Failed to save zip: ${msg}`)
    void vscode.window.showErrorMessage(`Could not save plugin zip: ${msg}`)
    return
  }

  outputChannel.appendLine(
    `[install] Saved ${zip.length}B plugin zip to ${target.fsPath}`
  )
  void vscode.window.showInformationMessage(
    `Saved ${bundleName}.zip to ${target.fsPath}.`,
    'Okay'
  )
}

// ---------------------------------------------------------------------------
// Drop the SKILL.md + references at `~/.claude/skills/{name}/`.
//
// VS Code Chat reads agent skills from `~/.claude/skills/` natively (along
// with `~/.copilot/skills/` and `~/.agents/skills/`) per the Agent Skills
// spec at agentskills.io. Claude Code reads the same path. Using one
// canonical location means installing for one target then the other does
// not duplicate the skill folder.
// ---------------------------------------------------------------------------

function writeSkillFolder(
  bundleName: string,
  entries: ReadonlyArray<ZipEntry>,
  outputChannel: vscode.OutputChannel
): void {
  const skillsRoot = path.join(os.homedir(), '.claude', 'skills', bundleName)

  // The bundle's skill content lives at
  // `{bundleName}/skills/{bundleName}/...`. Strip that prefix so files
  // land at `~/.claude/skills/{bundleName}/...` (matching the layout
  // both Claude Code and VS Code Chat expect for an installed skill).
  const skillPrefix = `${bundleName}/skills/${bundleName}/`
  let wrote = 0
  for (const e of entries) {
    if (!e.name.startsWith(skillPrefix)) continue
    const rel = e.name.slice(skillPrefix.length)
    if (!rel) continue
    const dest = path.join(skillsRoot, rel)
    // Belt-and-braces guard: refuse to escape the skill root even if
    // the zip somehow contains '..' segments.
    const resolved = path.resolve(dest)
    if (!resolved.startsWith(path.resolve(skillsRoot) + path.sep)) {
      outputChannel.appendLine(`[install] Refused unsafe entry path: ${e.name}`)
      continue
    }
    fs.mkdirSync(path.dirname(resolved), { recursive: true })
    fs.writeFileSync(resolved, e.content)
    wrote++
  }
  outputChannel.appendLine(
    `[install] Wrote ${wrote} skill file${wrote === 1 ? '' : 's'} to ${skillsRoot}`
  )
}

// ---------------------------------------------------------------------------
// Minimal STORE-only ZIP parser.
//
// The auth-proxy always writes uncompressed entries (method=0, gp-flag=0)
// so we don't need DEFLATE, encryption, or Zip64 support. We walk local
// file headers from the start and stop at the central directory
// signature. Anything more exotic in the input is a server-side bug.
// ---------------------------------------------------------------------------

interface ZipEntry {
  name: string
  content: Buffer
}

const LOCAL_FILE_HEADER = 0x04034b50
const CENTRAL_DIR_HEADER = 0x02014b50

function parseStoreZip(buf: Buffer): ZipEntry[] {
  const entries: ZipEntry[] = []
  let off = 0
  while (off + 30 <= buf.length) {
    const sig = buf.readUInt32LE(off)
    if (sig === CENTRAL_DIR_HEADER) break
    if (sig !== LOCAL_FILE_HEADER) {
      throw new Error(
        `Unexpected ZIP signature 0x${sig.toString(16)} at offset ${off}`
      )
    }
    const method = buf.readUInt16LE(off + 8)
    if (method !== 0) {
      throw new Error(`Unsupported compression method ${method} in plugin zip`)
    }
    const compressed = buf.readUInt32LE(off + 18)
    const nameLen = buf.readUInt16LE(off + 26)
    const extraLen = buf.readUInt16LE(off + 28)
    const nameStart = off + 30
    const dataStart = nameStart + nameLen + extraLen
    const name = buf.slice(nameStart, nameStart + nameLen).toString('utf-8')
    const content = buf.slice(dataStart, dataStart + compressed)
    entries.push({ name, content })
    off = dataStart + compressed
  }
  return entries
}
